import { randomUUID } from 'node:crypto';
import { requestFingerprint, validateSentOriginal, type SentOriginal } from './communication.rules';
const original = (): SentOriginal => ({ emailAccountId: randomUUID(), to: ['Persona@Example.test'], cc: [], bcc: [], subject: '  Asunto  original ', body: '  Hola\r\n\r\nFirma <script>texto</script> https://example.test  ', sentAt: '2000-01-01T12:00:00-04:00' });
describe('Original de comunicación enviada', () => {
  it('conserva exactamente espacios, saltos, mayúsculas y fechas históricas sin límite artificial', () => { const input = original(); expect(validateSentOriginal(input)).toBe(input); expect(input.body).toContain('\r\n\r\n'); });
  it.each([{ to: [] }, { to: ['mal'] }, { to: [' a@example.test'] }, { cc: null }, { bcc: ['bad'] }, { subject: ' ' }, { subject: 'a\nb' }, { body: ' ' }, { body: 'a\0b' }, { sentAt: '2999-01-01T00:00:00Z' }, { sentAt: '2020-02-30T00:00:00Z' }, { sentAt: '2020-01-01T00:00:00' }, { to: Array<string>(101).fill('a@example.test') }, { subject: 'a'.repeat(999) }, { body: 'a'.repeat(200001) }])('rechaza original inválido %j', patch => { expect(() => validateSentOriginal({ ...original(), ...patch } as SentOriginal)).toThrow('INVALID_COMMUNICATION'); });
  it('mantiene duplicados reales y orden por tipo', () => { const input = original(); input.to.push(input.to[0]); input.bcc = [...input.to]; expect(validateSentOriginal(input).to).toEqual(input.to); });
  it('huella identifica el original completo y canonicaliza solamente IDs y instante', () => { const input = original(), id = randomUUID(), hash = requestFingerprint(id, input); expect(requestFingerprint(id.toUpperCase(), { ...input, emailAccountId: input.emailAccountId.toUpperCase(), sentAt: '2000-01-01T16:00:00Z' })).toBe(hash); for (const patch of [{ body: input.body + ' ' }, { subject: input.subject + ' ' }, { to: ['persona@example.test'] }, { bcc: ['b@example.test'] }]) expect(requestFingerprint(id, { ...input, ...patch })).not.toBe(hash); expect(requestFingerprint(randomUUID(), input)).not.toBe(hash); });
});
