ALTER TYPE "AuditAction" ADD VALUE 'OPPORTUNITY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'OPPORTUNITY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'OPPORTUNITY_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'OPPORTUNITY_DISCARDED';
ALTER TYPE "AuditAction" ADD VALUE 'OPPORTUNITY_FINISHED';
