import { ActionLink, Button } from '../../components/ui/actions';
import { PageHeader, Surface, FilterBar } from '../../components/ui/layout';
import { FormField, Select, Textarea, FormSection, FormActions } from '../../components/ui/forms';
import { DataList, DataListItem, Metadata, Pagination } from '../../components/ui/lists';
import { EmptyState, QueryFeedback } from '../../components/ui/feedback';
import './meetings.css';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { useNavigate, useParams, useSearchParams } from 'react-router';
import { useSession, type AuthIdentity } from '../auth/session';
import { MutationError } from '../directory/directory-ui';
import { processesPageSchema } from '../relationships/process-contracts';
import { opportunityPageSchema } from '../opportunities/contracts';
import { Attachments } from '../files/attachments';
import { agreementsPageSchema, meetingEventsPageSchema, meetingSchema, meetingsPageSchema, participantsPageSchema, MEETING_STATUS_LABELS, type Meeting } from './contracts';
import { meetingIdentityKey, useMeetingCommand, useMeetingQuery } from './queries';
import { MeetingEventContent, MeetingSummary, MeetingStatus, ParticipantForm, ParticipantRow, PlanningFormView } from './meeting-components';
export function MeetingsPage(){const identity=useSession().data;if(!identity?.permissions.includes('meetings.read'))return <p role="alert">No tienes permiso para consultar reuniones.</p>;return <MeetingsList key={meetingIdentityKey(identity).join(':')} identity={identity}/>;}
function MeetingsList({identity}:{identity:AuthIdentity}){
 const [page,setPage]=useState(1),[status,setStatus]=useState('all'),[params]=useSearchParams();
 const filter=new URLSearchParams({page:String(page),...status!=='all'?{status}:{}});
 for(const key of ['processId','opportunityId']){const id=params.get(key);if(id&&z.uuid().safeParse(id).success)filter.set(key,id);}
 const query=useMeetingQuery(identity,'meetings?'+filter,meetingsPageSchema);
 return <section className="meetings-page"><PageHeader eyebrow="Planificación y seguimiento" title="Reuniones" description="Consulta la agenda institucional, los participantes y los acuerdos registrados." primaryAction={identity.permissions.includes('meetings.create')&&<ActionLink appearance="action" to="/meetings/new">Crear reunión</ActionLink>}/>
 <FilterBar aria-label="Filtros de reuniones" summary={query.data&&<p>{query.data.total} {query.data.total === 1 ? 'reunión encontrada' : 'reuniones encontradas'}</p>}><FormField label="Estado de reunión">{control=><Select {...control} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">Todos</option>{Object.entries(MEETING_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select>}</FormField></FilterBar>
 <QueryFeedback pending={query.isPending} error={query.isError} retry={query.refetch}/>
 {query.data?.total===0&&<EmptyState title="No hay reuniones para estos filtros."/>}<DataList>{query.data?.items.map(row=><DataListItem key={row.id}><div className="planning-row-heading"><ActionLink appearance="list" to={'/meetings/'+row.id}>Ver reunión: {row.purpose}</ActionLink><MeetingStatus row={row}/></div><MeetingSummary row={row}/></DataListItem>)}</DataList>{query.data&&<Pagination page={page} total={query.data.total} onPage={setPage}/>}</section>;
}
export function MeetingCreatePage(){const identity=useSession().data,[params]=useSearchParams();if(!identity?.permissions.includes('meetings.create'))return <p role="alert">No tienes permiso para crear reuniones.</p>;if(['processId','opportunityId'].some(key=>params.has(key)&&!z.uuid().safeParse(params.get(key)).success))return <p role="alert">El enlace de origen no es válido.</p>;return <CreateMeeting key={meetingIdentityKey(identity).join(':')+params.toString()} identity={identity} initialProcess={params.get('processId')} initialOpportunity={params.get('opportunityId')}/>;}
function CreateMeeting({identity,initialProcess,initialOpportunity}:{identity:AuthIdentity;initialProcess:string|null;initialOpportunity:string|null}){
 const [processId,setProcess]=useState(initialProcess),[opportunityId,setOpportunity]=useState(initialOpportunity),[processLabel,setProcessLabel]=useState(initialProcess?'Proceso de origen seleccionado':''),[opportunityLabel,setOpportunityLabel]=useState(initialOpportunity?'Oportunidad de origen seleccionada':''),[processPage,setProcessPage]=useState(1),[opportunityPage,setOpportunityPage]=useState(1);
 const processes=useMeetingQuery(identity,'relationship-processes?state=all&page='+processPage,processesPageSchema,!initialProcess&&identity.permissions.includes('relationships.process.read'),'meetings.create');
 const opportunities=useMeetingQuery(identity,'opportunities?status=all&page='+opportunityPage,opportunityPageSchema,!initialOpportunity&&identity.permissions.includes('opportunities.read'),'meetings.create');
 const mutation=useMeetingCommand(identity,'meetings.create'),navigate=useNavigate(),[originError,setOriginError]=useState<string|null>(null);
 return <section className="meetings-page"><PageHeader eyebrow="Planificación y seguimiento / Reuniones" title="Crear reunión" description="La reunión conserva su zona horaria y el origen institucional. Podrás incorporar participantes después de guardarla." actions={<ActionLink appearance="context" to="/meetings">Volver a reuniones</ActionLink>}/>
 <FormSection disabled={mutation.isPending} heading="Proceso u oportunidad">
 {processId&&<p>{processLabel} <ActionLink appearance="context" to={'/relationship-processes/'+processId}>Consultar proceso seleccionado</ActionLink>{!initialProcess&&<Button type="button" onClick={()=>setProcess(null)}>Quitar proceso</Button>}</p>}
 {!initialProcess&&<section aria-label="Seleccionar proceso"><QueryFeedback pending={processes.isPending} error={processes.isError} retry={processes.refetch}/><ul>{processes.data?.items.map(row=><li key={row.id}><Button type="button" onClick={()=>{setProcess(row.id);setProcessLabel(row.purpose);}}>Seleccionar proceso: {row.purpose}</Button></li>)}</ul>{processes.data&&<Pagination page={processPage} total={processes.data.total} onPage={setProcessPage}/>}</section>}
 {opportunityId&&<p>{opportunityLabel} <ActionLink appearance="context" to={'/opportunities/'+opportunityId}>Consultar oportunidad seleccionada</ActionLink>{!initialOpportunity&&<Button type="button" onClick={()=>setOpportunity(null)}>Quitar oportunidad</Button>}</p>}
 {!initialOpportunity&&<section aria-label="Seleccionar oportunidad"><QueryFeedback pending={opportunities.isPending} error={opportunities.isError} retry={opportunities.refetch}/><ul>{opportunities.data?.items.map(row=><li key={row.id}><Button type="button" onClick={()=>{setOpportunity(row.id);setOpportunityLabel(row.name);if(row.process&&!initialProcess){setProcess(row.process.id);setProcessLabel(row.process.purpose);}}}>Seleccionar oportunidad: {row.name}</Button></li>)}</ul>{opportunities.data&&<Pagination page={opportunityPage} total={opportunities.data.total} onPage={setOpportunityPage}/>}</section>}
 </FormSection>{originError&&<p role="alert">{originError}</p>}
 <PlanningFormView pending={mutation.isPending} label="Guardar reunión" submit={async body=>{if(!processId&&!opportunityId){setOriginError('Selecciona al menos un proceso o una oportunidad.');return;}setOriginError(null);const row=await mutation.mutateAsync({path:'meetings',body:{...body,processId,opportunityId}});navigate('/meetings/'+row.id);}}/><MutationError modern error={mutation.error}/></section>;
}
export function MeetingDetailPage(){const identity=useSession().data,{id=''}=useParams();if(!identity?.permissions.includes('meetings.read'))return <p role="alert">No tienes permiso para consultar reuniones.</p>;return <MeetingDetail key={meetingIdentityKey(identity).join(':')+id} identity={identity} id={id}/>;}
function MeetingDetail({identity,id}:{identity:AuthIdentity;id:string}){
 const query=useMeetingQuery(identity,'meetings/'+id,meetingSchema),[editing,setEditing]=useState(false),[participantPage,setParticipantPage]=useState(1),[agreementPage,setAgreementPage]=useState(1),[eventPage,setEventPage]=useState(1);
 const participants=useMeetingQuery(identity,'meetings/'+id+'/participants?page='+participantPage,participantsPageSchema,!!query.data),agreements=useMeetingQuery(identity,'meetings/'+id+'/agreements?page='+agreementPage,agreementsPageSchema,!!query.data),events=useMeetingQuery(identity,'meetings/'+id+'/events?page='+eventPage,meetingEventsPageSchema,!!query.data);
 const update=useMeetingCommand(identity,'meetings.update'),complete=useMeetingCommand(identity,'meetings.results'),row=query.data;
 return <section className="meetings-page"><PageHeader eyebrow="Planificación y seguimiento / Reuniones" title={row?.purpose ?? 'Reunión institucional'} metadata={row&&<MeetingStatus row={row}/>} actions={<ActionLink appearance="context" to="/meetings">Volver a reuniones</ActionLink>}/><QueryFeedback pending={query.isPending} error={query.isError} retry={query.refetch}/>
 {row&&<><Surface heading="Planificación y contexto"><MeetingSummary row={row}/><Metadata items={[{label:'Registrada por',value:row.createdBy.displayName},{label:'Fecha de registro',value:<time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleString('es-BO')}</time>}]} />
 {row.meetingUrl&&<p><a className="underline break-all" href={row.meetingUrl} target="_blank" rel="noreferrer">Enlace de reunión</a></p>}{row.location&&<p>Lugar: {row.location}</p>}{row.cancellationReason&&<p>Motivo de cancelación: {row.cancellationReason}</p>}</Surface>
 {row.canEdit&&identity.permissions.includes('meetings.update')&&<Button onClick={()=>setEditing(!editing)}>Editar planificación futura</Button>}
 {editing&&row.canEdit&&<PlanningFormView row={row} pending={update.isPending} label="Guardar planificación" submit={async body=>{await update.mutateAsync({path:'meetings/'+id,method:'PATCH',body:{...body,expectedVersion:row.version}});setEditing(false);}}/>}<MutationError modern error={update.error}/>
 {row.canComplete&&identity.permissions.includes('meetings.results')&&<Button variant="primary" disabled={complete.isPending} onClick={()=>complete.mutate({path:'meetings/'+id+'/complete',body:{expectedVersion:row.version}})}>Registrar reunión realizada</Button>}<MutationError modern error={complete.error}/>
 {row.status==='SCHEDULED'&&identity.permissions.includes('meetings.update')&&<CancelForm identity={identity} row={row}/>}
 <Button onClick={()=>void query.refetch()}>Recargar reunión y revisar cambios</Button>
 <Surface aria-label="Participantes de reunión" heading="Participantes de reunión" className="planning-history"><QueryFeedback pending={participants.isPending} error={participants.isError} retry={participants.refetch}/>{participants.data?.total===0&&<EmptyState title="No hay participantes incorporados."/>}
 {(['internal','external']as const).map(kind=><div key={kind}><h3 className="font-semibold">{kind==='internal'?'Equipo CECASEM':'Participantes externos'}</h3><ul className="space-y-2">{participants.data?.items.filter(participant=>kind==='internal'?!!participant.userId:!participant.userId).map(participant=><ParticipantRow key={participant.id+participant.attendance} identity={identity} row={row} participant={participant}/>)}</ul></div>)}
 {participants.data&&<Pagination page={participantPage} total={participants.data.total} onPage={setParticipantPage}/>}
 {row.status!=='CANCELLED'&&identity.permissions.includes('meetings.participants')&&<ParticipantForm identity={identity} row={row}/>}</Surface>
 <Surface aria-label="Acuerdos de reunión" heading="Acuerdos de reunión" className="planning-history"><QueryFeedback pending={agreements.isPending} error={agreements.isError} retry={agreements.refetch}/>{agreements.data?.total===0&&<EmptyState title="No hay acuerdos registrados."/>}<ol className="space-y-3">{agreements.data?.items.map(agreement=><li key={agreement.id} className="rounded border p-3"><p>{agreement.createdBy.displayName} · {new Date(agreement.createdAt).toLocaleString('es-BO')}</p><p className="whitespace-pre-wrap">{agreement.text}</p></li>)}</ol>{agreements.data&&<Pagination page={agreementPage} total={agreements.data.total} onPage={setAgreementPage}/>}
 {row.status==='COMPLETED'&&identity.permissions.includes('meetings.results')&&<AgreementForm identity={identity} row={row}/>}</Surface>
 <Attachments modern identity={identity} resource="meetings" resourceId={id} processId={row.processId??undefined} blocked={row.status==='CANCELLED'}/>
 <Surface aria-label="Historial de reunión" heading="Historial de reunión" className="planning-history"><QueryFeedback pending={events.isPending} error={events.isError} retry={events.refetch}/><ol className="space-y-3">{events.data?.items.map(event=><li key={event.id} className="rounded border p-3"><p>{event.actor.displayName} · {new Date(event.createdAt).toLocaleString('es-BO')}</p><MeetingEventContent event={event}/></li>)}</ol>{events.data&&<Pagination page={eventPage} total={events.data.total} onPage={setEventPage}/>}</Surface></>}
 </section>;
}
function CancelForm({identity,row}:{identity:AuthIdentity;row:Meeting}){
 const form=useForm<{reason:string}>({defaultValues:{reason:''}}),mutation=useMeetingCommand(identity,'meetings.update');
 return <form aria-label="Cancelar reunión" className="space-y-2 rounded border p-3" onSubmit={form.handleSubmit(async values=>{if(!values.reason.trim()){form.setError('reason',{message:'Indica el motivo.'});return;}try{await mutation.mutateAsync({path:'meetings/'+row.id+'/cancel',body:{expectedVersion:row.version,reason:values.reason}});form.reset();}catch{/* Conserva motivo. */}})}><FormSection heading="Cancelación de reunión"><FormField label="Motivo de cancelación" error={form.formState.errors.reason?.message}>{control => <><Textarea {...control} aria-label="Motivo de cancelación" maxLength={5000} disabled={mutation.isPending} {...form.register('reason')}/></>}</FormField><FormActions><Button type="submit" variant="danger" disabled={mutation.isPending}>Cancelar reunión conservando historial</Button></FormActions></FormSection><MutationError modern error={mutation.error}/></form>;
}
function AgreementForm({identity,row}:{identity:AuthIdentity;row:Meeting}){
 const form=useForm<{text:string}>({defaultValues:{text:''}}),mutation=useMeetingCommand(identity,'meetings.results');
 return <form aria-label="Agregar acuerdo" className="space-y-2" onSubmit={form.handleSubmit(async values=>{if(!values.text.trim()){form.setError('text',{message:'Indica el acuerdo.'});return;}try{await mutation.mutateAsync({path:'meetings/'+row.id+'/agreements',body:{expectedVersion:row.version,text:values.text}});form.reset();}catch{/* Conserva texto. */}})}><FormSection heading="Agregar acuerdo"><p>Los acuerdos anteriores se conservan. Registra aclaraciones como hechos posteriores.</p><FormField label="Nuevo acuerdo" error={form.formState.errors.text?.message}>{control => <><Textarea {...control} aria-label="Nuevo acuerdo" maxLength={5000} disabled={mutation.isPending} {...form.register('text')}/></>}</FormField><FormActions><Button type="submit" variant="primary" disabled={mutation.isPending}>Registrar acuerdo</Button></FormActions></FormSection><MutationError modern error={mutation.error}/></form>;
}
