import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link } from 'react-router';
import type { AuthIdentity } from '../auth/session';
import { buttonClass, Field, inputClass, MutationError, Pagination, QueryState } from '../directory/directory-ui';
import { DirectoryTargetPicker, type PickedDirectoryTarget } from '../directory/target-picker';
import { ATTENDANCE_LABELS, MEETING_EVENT_LABELS, MEETING_STATUS_LABELS, MODALITY_LABELS, meetingDate, meetingsPageSchema, meetingUserSchema, pageSchema, planningBody, planningFormSchema, type Meeting, type MeetingEvent, type MeetingParticipant, type PlanningForm } from './contracts';
import { useMeetingCommand, useMeetingQuery } from './queries';
import { ActionLink } from '../../components/ui/actions';
import { DataList, DataListItem, Pagination as UiPagination } from '../../components/ui/lists';
import { EmptyState, QueryFeedback, StatusBadge } from '../../components/ui/feedback';
export function MeetingSummary({row}:{row:Meeting}) {return <><p>{meetingDate(row.scheduledAt,row.timezone)}</p><p>{MEETING_STATUS_LABELS[row.status]} · {MODALITY_LABELS[row.modality]}</p><p className="whitespace-pre-wrap">{row.purpose}</p>{row.process&&<Link className="underline" to={'/relationship-processes/'+row.process.id}>Proceso: {row.process.purpose}</Link>}{row.opportunity&&<p><Link className="underline" to={'/opportunities/'+row.opportunity.id}>Oportunidad: {row.opportunity.name}</Link></p>}</>;}
export function ContextMeetings({identity,processId,opportunityId,modern=false}:{identity:AuthIdentity;processId?:string;opportunityId?:string;modern?:boolean}){
 const [page,setPage]=useState(1),filter=new URLSearchParams({...processId&&!opportunityId?{processId}:{},...opportunityId?{opportunityId}:{},page:String(page)});
 const query=useMeetingQuery(identity,'meetings?'+filter,meetingsPageSchema);
 if(!identity.permissions.includes('meetings.read'))return null;
 if(modern)return <section aria-label="Reuniones vinculadas" className="space-y-3"><h3>Reuniones vinculadas</h3>{identity.permissions.includes('meetings.create')&&<ActionLink appearance="context" to={'/meetings/new?'+new URLSearchParams({...processId?{processId}:{},...opportunityId?{opportunityId}:{}})}>Crear reunión desde este contexto</ActionLink>}
 <QueryFeedback pending={query.isPending} error={query.isError} retry={query.refetch}/>{query.data?.total===0&&<EmptyState title="No hay reuniones vinculadas."/>}<DataList>{query.data?.items.map(row=><DataListItem key={row.id}><ActionLink appearance="list" to={'/meetings/'+row.id}>{row.purpose}</ActionLink><p><time dateTime={row.scheduledAt}>{meetingDate(row.scheduledAt,row.timezone)}</time> · <StatusBadge>{MEETING_STATUS_LABELS[row.status]}</StatusBadge></p></DataListItem>)}</DataList>{query.data&&<UiPagination page={page} total={query.data.total} onPage={setPage}/>}</section>;
 return <section aria-label="Reuniones vinculadas" className="space-y-3"><h2 className="text-xl font-semibold">Reuniones vinculadas</h2>{identity.permissions.includes('meetings.create')&&<Link className={buttonClass} to={'/meetings/new?'+new URLSearchParams({...processId?{processId}:{},...opportunityId?{opportunityId}:{}})}>Crear reunión desde este contexto</Link>}
 <QueryState pending={query.isPending} error={query.isError} retry={query.refetch}/>{query.data?.total===0&&<p>No hay reuniones vinculadas.</p>}<ul className="space-y-3">{query.data?.items.map(row=><li key={row.id} className="rounded border p-3"><Link className="font-semibold underline" to={'/meetings/'+row.id}>{row.purpose}</Link><p>{meetingDate(row.scheduledAt,row.timezone)} · {MEETING_STATUS_LABELS[row.status]}</p></li>)}</ul>{query.data&&<Pagination page={page} total={query.data.total} onPage={setPage}/>}</section>;
}
export function PlanningFormView({row,pending,label,submit}:{row?:Meeting;pending:boolean;label:string;submit:(body:ReturnType<typeof planningBody>)=>Promise<void>}){
 const form=useForm<PlanningForm>({resolver:zodResolver(planningFormSchema),defaultValues:{scheduledLocal:row?.scheduledLocal??'',timezone:row?.timezone??'America/La_Paz',modality:row?.modality??'ONLINE',meetingUrl:row?.meetingUrl??'',location:row?.location??'',purpose:row?.purpose??'',disambiguation:''}});
 return <form aria-label={label} className="min-w-0 space-y-3" onSubmit={form.handleSubmit(async values=>{try{await submit(planningBody(values));}catch{/* Preserva el borrador. */}})}><fieldset disabled={pending} className="min-w-0 space-y-3">
 <Field label="Fecha y hora local" error={form.formState.errors.scheduledLocal?.message}><input aria-label="Fecha y hora local" type="datetime-local" className={inputClass} {...form.register('scheduledLocal')}/></Field>
 <Field label="Zona horaria IANA" error={form.formState.errors.timezone?.message}><input aria-label="Zona horaria IANA" className={inputClass} list="meeting-timezones" {...form.register('timezone')}/><datalist id="meeting-timezones">{['America/La_Paz','America/Lima','America/New_York','Europe/Madrid','UTC'].map(zone=><option key={zone} value={zone}/>)}</datalist></Field>
 <Field label="Hora repetida por cambio de horario"><select aria-label="Hora repetida por cambio de horario" className={inputClass} {...form.register('disambiguation')}><option value="">Sin elección; validar automáticamente</option><option value="earlier">Primera ocurrencia</option><option value="later">Segunda ocurrencia</option></select></Field>
 <Field label="Modalidad"><select aria-label="Modalidad" className={inputClass} {...form.register('modality')}>{Object.entries(MODALITY_LABELS).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></Field>
 <Field label="Enlace de reunión" error={form.formState.errors.meetingUrl?.message}><input aria-label="Enlace de reunión" className={inputClass} maxLength={2048} {...form.register('meetingUrl')}/></Field>
 <Field label="Lugar" error={form.formState.errors.location?.message}><input aria-label="Lugar" className={inputClass} maxLength={500} {...form.register('location')}/></Field>
 <Field label="Propósito de reunión" error={form.formState.errors.purpose?.message}><textarea aria-label="Propósito de reunión" className={inputClass} maxLength={5000} {...form.register('purpose')}/></Field>
 <button className={buttonClass} disabled={pending}>{pending?'Guardando…':label}</button></fieldset></form>;
}
export function ParticipantForm({identity,row}:{identity:AuthIdentity;row:Meeting}){
 const mutation=useMeetingCommand(identity,'meetings.participants'),[kind,setKind]=useState<'internal'|'person'|'text'>('internal'),[person,setPerson]=useState<PickedDirectoryTarget|null>(null),[internal,setInternal]=useState<{id:string;displayName:string}|null>(null),[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[page,setPage]=useState(1);
 useEffect(()=>{const timer=setTimeout(()=>{setDebounced(search);setPage(1);},350);return()=>clearTimeout(timer);},[search]);
 const users=useMeetingQuery(identity,'meetings/internal-users?'+new URLSearchParams({search:debounced,page:String(page)}),pageSchema(meetingUserSchema),kind==='internal','meetings.participants');
 const form=useForm<{nameSnapshot:string;organizationSnapshot:string;roleSnapshot:string}>({defaultValues:{nameSnapshot:'',organizationSnapshot:'',roleSnapshot:''}});
 return <form aria-label="Agregar participante" className="min-w-0 space-y-3 rounded border p-3" onSubmit={form.handleSubmit(async values=>{
  if(kind==='internal'&&!internal||kind==='person'&&!person||kind==='text'&&!values.nameSnapshot.trim()){form.setError('nameSnapshot',{message:'Selecciona una ficha o indica el nombre disponible.'});return;}
  try{await mutation.mutateAsync({path:'meetings/'+row.id+'/participants',body:{expectedVersion:row.version,userId:kind==='internal'?internal?.id:null,personId:kind==='person'?person?.id:null,nameSnapshot:values.nameSnapshot.trim()||null,organizationSnapshot:values.organizationSnapshot.trim()||null,roleSnapshot:values.roleSnapshot.trim()||null}});form.reset();setPerson(null);setInternal(null);}catch{/* Conserva la selección. */}
 })}><h3 className="font-semibold">Agregar participante</h3><fieldset disabled={mutation.isPending} className="min-w-0 space-y-3"><Field label="Tipo de participante"><select aria-label="Tipo de participante" className={inputClass} value={kind} onChange={e=>{setKind(e.target.value as typeof kind);form.clearErrors();}}><option value="internal">Equipo CECASEM</option><option value="person">Persona externa existente</option><option value="text">Externo con datos mencionados</option></select></Field>
 {kind==='internal'&&<><Field label="Buscar equipo CECASEM"><input aria-label="Buscar equipo CECASEM" className={inputClass} value={search} onChange={e=>setSearch(e.target.value)}/></Field><QueryState pending={users.isPending} error={users.isError} retry={users.refetch}/><ul>{users.data?.items.map(user=><li key={user.id}><button type="button" className={buttonClass} onClick={()=>setInternal(user)}>Seleccionar usuario: {user.displayName}</button></li>)}</ul>{users.data&&<Pagination page={page} total={users.data.total} onPage={setPage}/>}<p>{internal?'Equipo seleccionado: '+internal.displayName:'Selecciona un integrante del equipo.'}</p></>}
 {kind==='person'&&<DirectoryTargetPicker identity={identity} referralKind="PERSON" referenceDescription="Selecciona la persona que participará en la reunión. Se conserva una copia de los datos conocidos al incorporarla." selected={person} onSelect={setPerson}/>}
 {kind!=='internal'&&<Field label="Nombre mencionado" error={form.formState.errors.nameSnapshot?.message}><input aria-label="Nombre mencionado" className={inputClass} maxLength={400} {...form.register('nameSnapshot')}/></Field>}
 {kind==='internal'&&form.formState.errors.nameSnapshot&&<p role="alert">{form.formState.errors.nameSnapshot.message}</p>}
 <Field label="Organización mencionada"><input aria-label="Organización mencionada" className={inputClass} maxLength={300} {...form.register('organizationSnapshot')}/></Field><Field label="Cargo o rol"><input aria-label="Cargo o rol" className={inputClass} maxLength={300} {...form.register('roleSnapshot')}/></Field><p>Las fichas se reutilizan; los datos desconocidos pueden quedar sin completar.</p><button className={buttonClass} disabled={mutation.isPending}>{mutation.isPending?'Registrando…':'Incorporar participante'}</button></fieldset><MutationError error={mutation.error}/></form>;
}
export function ParticipantRow({identity,row,participant}:{identity:AuthIdentity;row:Meeting;participant:MeetingParticipant}){
 const [attendance,setAttendance]=useState(participant.attendance),mutation=useMeetingCommand(identity,'meetings.results');
 return <li className="min-w-0 space-y-2 rounded border p-3 break-words"><p className="font-semibold">{participant.nameSnapshot}</p>{participant.organizationSnapshot&&<p>{participant.organizationSnapshot}</p>}{participant.roleSnapshot&&<p>{participant.roleSnapshot}</p>}<p>Asistencia: {ATTENDANCE_LABELS[participant.attendance]}</p>
 {participant.personId&&<Link className="underline" to={'/people/'+participant.personId}>Ficha de persona</Link>}
 {row.status==='COMPLETED'&&identity.permissions.includes('meetings.results')&&<form onSubmit={e=>{e.preventDefault();mutation.mutate({path:'meetings/'+row.id+'/participants/'+participant.id+'/attendance',method:'PATCH',body:{expectedVersion:row.version,attendance}});}} className="flex flex-wrap gap-2"><label>Asistencia de {participant.nameSnapshot}<select aria-label={'Asistencia de '+participant.nameSnapshot} className={inputClass} value={attendance} onChange={e=>setAttendance(e.target.value as typeof attendance)} disabled={mutation.isPending}>{Object.entries(ATTENDANCE_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className={buttonClass} disabled={mutation.isPending}>Registrar asistencia</button></form>}<MutationError error={mutation.error}/></li>;
}
export function MeetingEventContent({event}:{event:Pick<MeetingEvent,'type'|'snapshot'|'changes'>}){
 const snapshot=event.snapshot,changes=event.changes;
 return <><h3 className="font-semibold">{MEETING_EVENT_LABELS[event.type]}</h3><p>{snapshot.purpose}</p><p>Fecha programada: {meetingDate(snapshot.scheduledAt,snapshot.timezone)}</p><p>{MODALITY_LABELS[snapshot.modality]} · {snapshot.participantCount} participantes</p>{snapshot.opportunity&&<Link className="underline" to={'/opportunities/'+snapshot.opportunity.id}>Oportunidad: {snapshot.opportunity.name}</Link>}
 {typeof changes.text==='string'&&<p className="whitespace-pre-wrap">Acuerdo: {changes.text}</p>}{typeof changes.reason==='string'&&<p>Motivo: {changes.reason}</p>}{typeof changes.nameSnapshot==='string'&&<p>Participante: {changes.nameSnapshot}</p>}{typeof changes.previous==='string'&&typeof changes.next==='string'&&<p>Asistencia: {ATTENDANCE_LABELS[changes.previous as keyof typeof ATTENDANCE_LABELS]} → {ATTENDANCE_LABELS[changes.next as keyof typeof ATTENDANCE_LABELS]}</p>}
 {changes.participant&&typeof changes.participant==='object'&&'nameSnapshot'in changes.participant&&<p>Participante incorporado: {String(changes.participant.nameSnapshot)}</p>}
 {event.type==='UPDATED'&&changes.previous&&typeof changes.previous==='object'&&'scheduledAt'in changes.previous&&'timezone'in changes.previous&&<div className="space-y-1"><p>Fecha anterior: {meetingDate(String(changes.previous.scheduledAt),String(changes.previous.timezone))}</p>{'purpose'in changes.previous&&<p className="whitespace-pre-wrap">Propósito anterior: {String(changes.previous.purpose)}</p>}{'modality'in changes.previous&&<p>Modalidad anterior: {MODALITY_LABELS[changes.previous.modality as keyof typeof MODALITY_LABELS]}</p>}{'meetingUrl'in changes.previous&&typeof changes.previous.meetingUrl==='string'&&<p className="break-all">Enlace anterior: {changes.previous.meetingUrl}</p>}{'location'in changes.previous&&typeof changes.previous.location==='string'&&<p>Lugar anterior: {changes.previous.location}</p>}</div>}</>;
}
