import { beforeEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router';
import { createQueryClient } from '../../lib/query/query-client';
import { AUTH_QUERY_KEY, type AuthIdentity } from '../auth/session';
import { MeetingCreatePage, MeetingDetailPage, MeetingsPage } from './meetings-pages';
import { meetingDate, planningFormSchema, type Meeting, type MeetingParticipant } from './contracts';
import { clearForbiddenMeetings, meetingIdentityKey } from './queries';
import { clearForbiddenTimeline, timelineIdentityKey } from '../relationships/timeline-queries';
const id='11111111-1111-4111-8111-111111111111',processId='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444';
const identity:AuthIdentity={id:'22222222-2222-4222-8222-222222222222',givenNames:'Ana',familyNames:'QA',username:'ana',email:'ana@example.test',role:'RESEARCH',permissions:['meetings.read','meetings.create','meetings.update','meetings.participants','meetings.results','relationships.process.read','opportunities.read','directory.read','files.read','files.upload']};
const user={id:identity.id,displayName:'Ana QA',isActive:true};
const fixture:Meeting={id,processId,opportunityId:null,scheduledAt:'2099-10-15T14:00:00.000Z',scheduledLocal:'2099-10-15T10:00',timezone:'America/La_Paz',modality:'ONLINE',meetingUrl:null,location:null,purpose:'Cooperación regional',status:'SCHEDULED',completedAt:null,cancelledAt:null,cancellationReason:null,version:1,createdAt:'2026-10-04T00:00:00.000Z',updatedAt:'2026-10-04T00:00:00.000Z',createdBy:user,process:{id:processId,purpose:'Proceso institucional'},opportunity:null,participantCount:0,agreementCount:0,canEdit:true,canComplete:false};
describe('Reuniones: formularios, resultados, conflictos y privacidad',()=>{
 let client=createQueryClient(),row:Meeting,participants:MeetingParticipant[],agreements:{id:string;meetingId:string;text:string;createdAt:string;createdBy:typeof user}[],failure=0,total=1;
 const fetchMock=vi.fn<(url:string,options?:RequestInit)=>Promise<Response>>();
 const page=(items:unknown[],count=items.length)=>({items,total:count,page:1,pageSize:25});
 beforeEach(()=>{client=createQueryClient();client.setQueryData(AUTH_QUERY_KEY,identity);row=structuredClone(fixture);participants=[];agreements=[];failure=0;total=1;fetchMock.mockReset();fetchMock.mockImplementation(async(url,options)=>{
  if(url.endsWith('/auth/me'))return Response.json(client.getQueryData(AUTH_QUERY_KEY));
  if(options?.method==='POST'||options?.method==='PATCH'){
   if(failure)return Response.json({code:'VERSION_CONFLICT'},{status:failure});
   const body=JSON.parse(options.body as string) as Record<string,unknown>;
   if(url.endsWith('/cancel'))row={...row,status:'CANCELLED',cancellationReason:String(body.reason),canEdit:false,canComplete:false};
   else if(url.endsWith('/complete'))row={...row,status:'COMPLETED',completedAt:'2026-10-04T00:00:00.000Z',canEdit:false,canComplete:false};
   else if(url.endsWith('/participants')){participants.push({id:other,meetingId:id,userId:body.userId as string|null,personId:body.personId as string|null,nameSnapshot:body.userId?'Ana QA':String(body.nameSnapshot),organizationSnapshot:body.organizationSnapshot as string|null,roleSnapshot:body.roleSnapshot as string|null,attendance:'UNKNOWN',createdAt:row.createdAt,createdBy:user});row={...row,participantCount:participants.length};}
   else if(url.endsWith('/attendance'))participants=participants.map(p=>({...p,attendance:body.attendance as MeetingParticipant['attendance']}));
   else if(url.endsWith('/agreements')){agreements.push({id:other,meetingId:id,text:String(body.text),createdAt:row.createdAt,createdBy:user});row={...row,agreementCount:agreements.length};}
   else row={...row,...body} as Meeting;
   row={...row,version:row.version+1};return Response.json(row,{status:options.method==='POST'?201:200});
  }
  if(url.includes('/internal-users?'))return Response.json(page([user]));
  if(url.includes('/participants?'))return Response.json(page(participants));
  if(url.includes('/agreements?'))return Response.json(page(agreements));
  if(url.includes('/events?')||url.includes('/attachments?')||url.includes('/opportunities?')||url.includes('/relationship-processes?'))return Response.json(page([]));
  if(url.endsWith('/files/config'))return Response.json({maxBytes:20971520,maxFiles:10});
  if(url.includes('/meetings?'))return Response.json(page(total?[row]:[],total));
  if(url.endsWith('/meetings/'+id))return Response.json(row);
  return new Response(null,{status:404});
 });vi.stubGlobal('fetch',fetchMock);});
 function view(path='/meetings/'+id){return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><Routes><Route path="meetings" element={<MeetingsPage/>}/><Route path="meetings/new" element={<MeetingCreatePage/>}/><Route path="meetings/:id" element={<MeetingDetailPage/>}/></Routes></MemoryRouter></QueryClientProvider>);}
 const commands=()=>fetchMock.mock.calls.filter(([,options])=>['POST','PATCH'].includes(options?.method??''));
 const body=(index=0)=>JSON.parse(commands()[index]?.[1]?.body as string) as Record<string,unknown>;
 it.each([[0, '0 reuniones encontradas'], [1, '1 reunión encontrada'], [3, '3 reuniones encontradas']] as const)('contador concuerda con %i reuniones', async (count, expected) => {
  total = count; view('/meetings');
  expect(await screen.findByText(expected)).toBeVisible();
 });
 it('UI 2.8 detalle tiene propósito único, contexto y fechas semánticas separadas',async()=>{
  row={...row,opportunityId:other,opportunity:{id:other,name:'Convocatoria regional'}};view();await screen.findByRole('heading',{level:1,name:row.purpose});expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  const region=screen.getByRole('region',{name:'Planificación y contexto'});expect(region.querySelector('time')).toHaveAttribute('datetime',row.scheduledAt);expect(within(region).getByText('Fecha de registro').parentElement?.querySelector('time')).toHaveAttribute('datetime',row.createdAt);
  expect(screen.getByRole('link',{name:'Proceso: Proceso institucional'})).toHaveAttribute('href','/relationship-processes/'+processId);expect(screen.getByRole('link',{name:'Oportunidad: Convocatoria regional'})).toHaveAttribute('href','/opportunities/'+other);expect(commands()).toHaveLength(0);
 });
 it.each(['ADMINISTRATOR','RESEARCH','BOARD','PLANNING']as const)('UI 2.8 %s conserva lectura sin acciones al faltar capabilities',async role=>{
  client.setQueryData(AUTH_QUERY_KEY,{...identity,role,permissions:['meetings.read']});row={...row,canEdit:false,canComplete:false};view();await screen.findByRole('heading',{level:1,name:fixture.purpose});
  expect(screen.queryByRole('button',{name:'Editar planificación futura'})).not.toBeInTheDocument();expect(screen.queryByLabelText('Tipo de participante')).not.toBeInTheDocument();expect(screen.queryByLabelText('Motivo de cancelación')).not.toBeInTheDocument();
  await userEvent.click(screen.getByRole('link',{name:'Volver a reuniones'}));await screen.findByRole('heading',{level:1,name:'Reuniones'});expect(screen.queryByRole('link',{name:'Crear reunión'})).not.toBeInTheDocument();
 });
 it('UI 2.8 formulario conserva desambiguación, zona y validación accesible',async()=>{
  view('/meetings/new?processId='+processId);await userEvent.click(screen.getByRole('button',{name:'Guardar reunión'}));expect(screen.getByLabelText('Fecha y hora local')).toHaveAttribute('aria-invalid','true');expect(screen.getByLabelText('Propósito de reunión')).toHaveAttribute('aria-describedby');
  fireEvent.change(screen.getByLabelText('Fecha y hora local'),{target:{value:'2099-10-15T10:00'}});await userEvent.selectOptions(screen.getByLabelText('Hora repetida por cambio de horario'),'later');await userEvent.type(screen.getByLabelText('Propósito de reunión'),'Mesa');await userEvent.click(screen.getByRole('button',{name:'Guardar reunión'}));await screen.findByRole('heading',{level:1,name:'Mesa'});expect(body()).toMatchObject({scheduledLocal:'2099-10-15T10:00',timezone:'America/La_Paz',disambiguation:'later'});
 });
 it('UI 2.8 grupos conservan internos y externos con snapshots y ficha',async()=>{
  participants=[{id:other,meetingId:id,userId:identity.id,personId:null,nameSnapshot:'Equipo interno',organizationSnapshot:null,roleSnapshot:null,attendance:'UNKNOWN',createdAt:row.createdAt,createdBy:user},{id:processId,meetingId:id,userId:null,personId:other,nameSnapshot:'Persona externa',organizationSnapshot:'Entidad externa',roleSnapshot:'Representante',attendance:'UNKNOWN',createdAt:row.createdAt,createdBy:user}];view();await screen.findByText('Persona externa');
  const region=screen.getByRole('region',{name:'Participantes de reunión'});expect(within(region).getByRole('heading',{name:'Equipo CECASEM'}).parentElement).toHaveTextContent('Equipo interno');expect(within(region).getByRole('heading',{name:'Participantes externos'}).parentElement).toHaveTextContent('Entidad externa');expect(screen.getByRole('link',{name:'Ficha de persona'})).toHaveAttribute('href','/people/'+other);
 });
 it('UI 2.8 realización mantiene comando explícito y versión sin nuevas confirmaciones',async()=>{
  row={...row,canComplete:true,canEdit:false};view();await userEvent.click(await screen.findByRole('button',{name:'Registrar reunión realizada'}));await screen.findByText('Realizada');expect(body()).toEqual({expectedVersion:1});expect(commands()[0]?.[0]).toContain('/complete');
 });
 it('lista fecha en la zona original y filtra estado',async()=>{view('/meetings');await screen.findByRole('link',{name:'Ver reunión: Cooperación regional'});expect(screen.getByText(/10:00 · America\/La_Paz/)).toBeInTheDocument();await userEvent.selectOptions(screen.getByLabelText('Estado de reunión'),'COMPLETED');await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>url.includes('status=COMPLETED'))).toBe(true));});
 it('pagina sin cargar todas las reuniones',async()=>{total=26;view('/meetings');await screen.findByRole('link',{name:/Ver reunión/});await userEvent.click(screen.getByRole('button',{name:'Siguiente'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>url.includes('/meetings?page=2'))).toBe(true));});
 it('muestra vacío y permite crear',async()=>{total=0;view('/meetings');await screen.findByText('No hay reuniones para estos filtros.');expect(screen.getByRole('link',{name:'Crear reunión'})).toHaveAttribute('href','/meetings/new');});
 it('muestra error sin revelar datos técnicos y permite reintentar',async()=>{fetchMock.mockImplementation(async()=>new Response(null,{status:500}));view('/meetings');await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Reintentar'})).toBeInTheDocument();expect(screen.queryByText('Cooperación regional')).not.toBeInTheDocument();});
 it('muestra carga mientras la petición sigue pendiente',async()=>{fetchMock.mockImplementation(()=>new Promise(()=>{}));view('/meetings');expect(screen.getByText('Cargando…')).toBeInTheDocument();});
 it('crea desde un proceso real con zona explícita y clave idempotente',async()=>{view('/meetings/new?processId='+processId);fireEvent.change(screen.getByLabelText('Fecha y hora local'),{target:{value:'2099-10-15T10:00'}});await userEvent.type(screen.getByLabelText('Propósito de reunión'),'Mesa regional');await userEvent.click(screen.getByRole('button',{name:'Guardar reunión'}));await screen.findByRole('heading',{level:1,name:'Mesa regional'});expect(body()).toMatchObject({processId,opportunityId:null,timezone:'America/La_Paz',scheduledLocal:'2099-10-15T10:00',purpose:'Mesa regional'});expect(new Headers(commands()[0]?.[1]?.headers).get('Idempotency-Key')).toMatch(/^[0-9a-f-]{36}$/);});
 it('impide crear sin origen y no inventa entidades',async()=>{view('/meetings/new');fireEvent.change(screen.getByLabelText('Fecha y hora local'),{target:{value:'2099-10-15T10:00'}});await userEvent.type(screen.getByLabelText('Propósito de reunión'),'Mesa');await userEvent.click(screen.getByRole('button',{name:'Guardar reunión'}));await screen.findByText('Selecciona al menos un proceso o una oportunidad.');expect(commands()).toHaveLength(0);});
 it('rechaza un enlace de origen inválido antes de consultar reuniones',async()=>{view('/meetings/new?processId=invalid');await screen.findByText('El enlace de origen no es válido.');expect(fetchMock.mock.calls.some(([url])=>url.includes('/meetings'))).toBe(false);});
 it('detalle futuro ofrece archivos, conserva la zona y no permite resultados',async()=>{view();await screen.findByRole('button',{name:'Editar planificación futura'});expect(screen.getByText(/America\/La_Paz/)).toBeInTheDocument();expect(screen.getByLabelText('Seleccionar archivos')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Registrar reunión realizada'})).not.toBeInTheDocument();expect(screen.queryByLabelText('Nuevo acuerdo')).not.toBeInTheDocument();});
 it('conserva borrador y key al reintentar 409; recargar conserva texto y toma nueva versión',async()=>{failure=409;view();await userEvent.click(await screen.findByRole('button',{name:'Editar planificación futura'}));await userEvent.clear(screen.getByLabelText('Propósito de reunión'));await userEvent.type(screen.getByLabelText('Propósito de reunión'),'Borrador revisado');await userEvent.click(screen.getByRole('button',{name:'Guardar planificación'}));await screen.findByText(/Otra persona cambió la reunión/);await userEvent.click(screen.getByRole('button',{name:'Guardar planificación'}));await waitFor(()=>expect(commands()).toHaveLength(2));expect(new Headers(commands()[0]?.[1]?.headers).get('Idempotency-Key')).toBe(new Headers(commands()[1]?.[1]?.headers).get('Idempotency-Key'));row={...row,version:2,purpose:'Cambio externo'};await userEvent.click(screen.getByRole('button',{name:'Recargar reunión y revisar cambios'}));await screen.findByText('Cambio externo');expect(screen.getByLabelText('Propósito de reunión')).toHaveValue('Borrador revisado');failure=0;await userEvent.click(screen.getByRole('button',{name:'Guardar planificación'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Guardar planificación'})).not.toBeInTheDocument());expect(body(2)).toMatchObject({expectedVersion:2,purpose:'Borrador revisado'});});
 it('incorpora usuario interno por ID sin simular asistencia',async()=>{view();await userEvent.click(await screen.findByRole('button',{name:'Seleccionar usuario: Ana QA'}));await userEvent.click(screen.getByRole('button',{name:'Incorporar participante'}));await screen.findByText('Asistencia: Sin registrar');expect(body()).toMatchObject({userId:identity.id,personId:null,nameSnapshot:null,expectedVersion:1});expect(screen.queryByLabelText('Asistencia de Ana QA')).not.toBeInTheDocument();});
 it('participante textual no crea ficha Person y conserva datos incompletos',async()=>{view();await screen.findByLabelText('Tipo de participante');await userEvent.selectOptions(screen.getByLabelText('Tipo de participante'),'text');await userEvent.type(screen.getByLabelText('Nombre mencionado'),'María mencionada');await userEvent.click(screen.getByRole('button',{name:'Incorporar participante'}));await screen.findByText('María mencionada');expect(body()).toMatchObject({userId:null,personId:null,nameSnapshot:'María mencionada',organizationSnapshot:null,roleSnapshot:null});expect(commands().every(([url])=>url.includes('/meetings/'))).toBe(true);});
 it('asistencia es explícita y utiliza la versión actual',async()=>{row={...row,status:'COMPLETED',canEdit:false};participants=[{id:other,meetingId:id,userId:identity.id,personId:null,nameSnapshot:'Ana QA',organizationSnapshot:null,roleSnapshot:null,attendance:'UNKNOWN',createdAt:row.createdAt,createdBy:user}];view();await screen.findByLabelText('Asistencia de Ana QA');expect(commands()).toHaveLength(0);await userEvent.selectOptions(screen.getByLabelText('Asistencia de Ana QA'),'ATTENDED');await userEvent.click(screen.getByRole('button',{name:'Registrar asistencia'}));await screen.findByText('Asistencia: Asistió');expect(body()).toMatchObject({attendance:'ATTENDED',expectedVersion:1});});
 it('acuerdos se agregan sin ofrecer edición ni perder anteriores',async()=>{row={...row,status:'COMPLETED',canEdit:false};agreements=[{id:processId,meetingId:id,text:'Acuerdo original',createdAt:row.createdAt,createdBy:user}];view();await screen.findByLabelText('Nuevo acuerdo');await userEvent.type(screen.getByLabelText('Nuevo acuerdo'),'Aclaración posterior');await userEvent.click(screen.getByRole('button',{name:'Registrar acuerdo'}));await screen.findByText('Aclaración posterior');expect(screen.getByText('Acuerdo original')).toBeInTheDocument();expect(body()).toMatchObject({text:'Aclaración posterior',expectedVersion:1});expect(screen.queryByRole('button',{name:/Editar acuerdo/})).not.toBeInTheDocument();});
 it('cancelar exige motivo y bloquea nuevas cargas conservando sección de archivos',async()=>{view();await screen.findByLabelText('Motivo de cancelación');await userEvent.click(screen.getByRole('button',{name:'Cancelar reunión conservando historial'}));await screen.findByText('Indica el motivo.');expect(commands()).toHaveLength(0);await userEvent.type(screen.getByLabelText('Motivo de cancelación'),'Cambio institucional');await userEvent.click(screen.getByRole('button',{name:'Cancelar reunión conservando historial'}));await screen.findByText('Motivo de cancelación: Cambio institucional');expect(screen.queryByLabelText('Seleccionar archivos')).not.toBeInTheDocument();expect(screen.queryByLabelText('Tipo de participante')).not.toBeInTheDocument();});
 it('sin capability no consulta ni muestra detalles',async()=>{client.setQueryData(AUTH_QUERY_KEY,{...identity,permissions:[]});view();await screen.findByText('No tienes permiso para consultar reuniones.');expect(fetchMock.mock.calls.some(([url])=>url.includes('/meetings/'))).toBe(false);});
 it('cambio de identidad o contexto autorizado retira caché sensible',async()=>{client.setQueryData([...meetingIdentityKey(identity),'meetings/'+id],fixture);await act(()=>clearForbiddenMeetings(client,{...identity,id:other}));expect(client.getQueriesData({queryKey:['meetings']})).toEqual([]);client.setQueryData([...meetingIdentityKey(identity),'meetings/'+id],fixture);await act(()=>clearForbiddenMeetings(client,{...identity,permissions:identity.permissions.filter(p=>p!=='relationships.process.read')}));expect(client.getQueriesData({queryKey:['meetings']})).toEqual([]);});
 it.each(['opportunities.read','files.read'])('retira también el timeline si se pierde contexto %s',async permission=>{const reader={...identity,permissions:[...identity.permissions,'communications.read']};client.setQueryData([...timelineIdentityKey(reader),processId],{pages:[{items:[{kind:'MEETING_ACTIVITY'}]}]});await act(()=>clearForbiddenTimeline(client,{...reader,permissions:reader.permissions.filter(p=>p!==permission)}));expect(client.getQueriesData({queryKey:['relationship-timeline']})).toEqual([]);});
 it('respuesta tardía no incorpora datos de otra identidad',async()=>{let resolve!:(response:Response)=>void;fetchMock.mockImplementation(url=>url.includes('/meetings/')?new Promise<Response>(done=>{resolve=done;}):Promise.resolve(Response.json(identity)));view();await waitFor(()=>expect(resolve).toBeTypeOf('function'));await act(async()=>{client.setQueryData(AUTH_QUERY_KEY,{...identity,id:other});await clearForbiddenMeetings(client,{...identity,id:other});resolve(Response.json(fixture));});expect(client.getQueryData([...meetingIdentityKey(identity),'meetings/'+id])).toBeUndefined();});
 it('fecha muestra la zona original aunque UTC esté en otro día; formulario rechaza modalidad incoherente',()=>{expect(meetingDate('2026-10-05T02:00:00.000Z','America/La_Paz')).toContain('4/10/26');const values={scheduledLocal:'2099-10-15T10:00',timezone:'America/La_Paz',disambiguation:'',modality:'ONLINE',meetingUrl:'',location:'Oficina',purpose:'Mesa'};expect(planningFormSchema.safeParse(values).success).toBe(false);expect(planningFormSchema.safeParse({...values,location:'',meetingUrl:'javascript:alert(1)'}).success).toBe(false);});
});
