import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router';
import { useSession, type AuthIdentity } from '../auth/session';
import { buttonClass, Field, inputClass, MutationError, Pagination, QueryState } from '../directory/directory-ui';
import { processesPageSchema } from '../relationships/process-contracts';
import { opportunityPageSchema } from '../opportunities/contracts';
import { Attachments } from '../files/attachments';
import { agreementsPageSchema, meetingEventsPageSchema, meetingSchema, meetingsPageSchema, participantsPageSchema, MEETING_STATUS_LABELS, type Meeting } from './contracts';
import { meetingIdentityKey, useMeetingCommand, useMeetingQuery } from './queries';
import { MeetingEventContent, MeetingSummary, ParticipantForm, ParticipantRow, PlanningFormView } from './meeting-components';
export function MeetingsPage(){const identity=useSession().data;if(!identity?.permissions.includes('meetings.read'))return <p role="alert">No tienes permiso para consultar reuniones.</p>;return <MeetingsList key={meetingIdentityKey(identity).join(':')} identity={identity}/>;}
function MeetingsList({identity}:{identity:AuthIdentity}){
 const [page,setPage]=useState(1),[status,setStatus]=useState('all'),[params]=useSearchParams();
 const filter=new URLSearchParams({page:String(page),...status!=='all'?{status}:{}});
 for(const key of ['processId','opportunityId']){const id=params.get(key);if(id&&z.uuid().safeParse(id).success)filter.set(key,id);}
 const query=useMeetingQuery(identity,'meetings?'+filter,meetingsPageSchema);
 return <section className="min-w-0 space-y-4 break-words"><h1 className="text-2xl font-semibold">Reuniones</h1>{identity.permissions.includes('meetings.create')&&<Link className={buttonClass} to="/meetings/new">Crear reunión</Link>}<Field label="Estado de reunión"><select aria-label="Estado de reunión" className={inputClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">Todos</option>{Object.entries(MEETING_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><QueryState pending={query.isPending} error={query.isError} retry={query.refetch}/>
 {query.data?.total===0&&<p>No hay reuniones para estos filtros.</p>}<ul className="space-y-3">{query.data?.items.map(row=><li key={row.id} className="rounded border p-3"><Link className="font-semibold underline" to={'/meetings/'+row.id}>Ver reunión: {row.purpose}</Link><MeetingSummary row={row}/></li>)}</ul>{query.data&&<Pagination page={page} total={query.data.total} onPage={setPage}/>}</section>;
}
export function MeetingCreatePage(){const identity=useSession().data,[params]=useSearchParams();if(!identity?.permissions.includes('meetings.create'))return <p role="alert">No tienes permiso para crear reuniones.</p>;if(['processId','opportunityId'].some(key=>params.has(key)&&!z.uuid().safeParse(params.get(key)).success))return <p role="alert">El enlace de origen no es válido.</p>;return <CreateMeeting key={meetingIdentityKey(identity).join(':')+params.toString()} identity={identity} initialProcess={params.get('processId')} initialOpportunity={params.get('opportunityId')}/>;}
function CreateMeeting({identity,initialProcess,initialOpportunity}:{identity:AuthIdentity;initialProcess:string|null;initialOpportunity:string|null}){
 const [processId,setProcess]=useState(initialProcess),[opportunityId,setOpportunity]=useState(initialOpportunity),[processLabel,setProcessLabel]=useState(initialProcess?'Proceso de origen seleccionado':''),[opportunityLabel,setOpportunityLabel]=useState(initialOpportunity?'Oportunidad de origen seleccionada':''),[processPage,setProcessPage]=useState(1),[opportunityPage,setOpportunityPage]=useState(1);
 const processes=useMeetingQuery(identity,'relationship-processes?state=all&page='+processPage,processesPageSchema,!initialProcess&&identity.permissions.includes('relationships.process.read'),'meetings.create');
 const opportunities=useMeetingQuery(identity,'opportunities?status=all&page='+opportunityPage,opportunityPageSchema,!initialOpportunity&&identity.permissions.includes('opportunities.read'),'meetings.create');
 const mutation=useMeetingCommand(identity,'meetings.create'),navigate=useNavigate(),[originError,setOriginError]=useState<string|null>(null);
 return <section className="min-w-0 space-y-4 break-words"><h1 className="text-2xl font-semibold">Crear reunión</h1><p>La reunión conserva su zona horaria y el origen institucional. Podrás incorporar participantes después de guardarla.</p><Link className="underline" to="/meetings">Volver a reuniones</Link>
 <fieldset disabled={mutation.isPending} className="min-w-0 space-y-3"><legend className="font-semibold">Proceso u oportunidad</legend>
 {processId&&<p>{processLabel} <Link className="underline" to={'/relationship-processes/'+processId}>Consultar proceso seleccionado</Link>{!initialProcess&&<button type="button" className={buttonClass} onClick={()=>setProcess(null)}>Quitar proceso</button>}</p>}
 {!initialProcess&&<section aria-label="Seleccionar proceso"><QueryState pending={processes.isPending} error={processes.isError} retry={processes.refetch}/><ul>{processes.data?.items.map(row=><li key={row.id}><button type="button" className={buttonClass} onClick={()=>{setProcess(row.id);setProcessLabel(row.purpose);}}>Seleccionar proceso: {row.purpose}</button></li>)}</ul>{processes.data&&<Pagination page={processPage} total={processes.data.total} onPage={setProcessPage}/>}</section>}
 {opportunityId&&<p>{opportunityLabel} <Link className="underline" to={'/opportunities/'+opportunityId}>Consultar oportunidad seleccionada</Link>{!initialOpportunity&&<button type="button" className={buttonClass} onClick={()=>setOpportunity(null)}>Quitar oportunidad</button>}</p>}
 {!initialOpportunity&&<section aria-label="Seleccionar oportunidad"><QueryState pending={opportunities.isPending} error={opportunities.isError} retry={opportunities.refetch}/><ul>{opportunities.data?.items.map(row=><li key={row.id}><button type="button" className={buttonClass} onClick={()=>{setOpportunity(row.id);setOpportunityLabel(row.name);if(row.process&&!initialProcess){setProcess(row.process.id);setProcessLabel(row.process.purpose);}}}>Seleccionar oportunidad: {row.name}</button></li>)}</ul>{opportunities.data&&<Pagination page={opportunityPage} total={opportunities.data.total} onPage={setOpportunityPage}/>}</section>}
 </fieldset>{originError&&<p role="alert">{originError}</p>}
 <PlanningFormView pending={mutation.isPending} label="Guardar reunión" submit={async body=>{if(!processId&&!opportunityId){setOriginError('Selecciona al menos un proceso o una oportunidad.');return;}setOriginError(null);const row=await mutation.mutateAsync({path:'meetings',body:{...body,processId,opportunityId}});navigate('/meetings/'+row.id);}}/><MutationError error={mutation.error}/></section>;
}
export function MeetingDetailPage(){const identity=useSession().data,{id=''}=useParams();if(!identity?.permissions.includes('meetings.read'))return <p role="alert">No tienes permiso para consultar reuniones.</p>;return <MeetingDetail key={meetingIdentityKey(identity).join(':')+id} identity={identity} id={id}/>;}
function MeetingDetail({identity,id}:{identity:AuthIdentity;id:string}){
 const query=useMeetingQuery(identity,'meetings/'+id,meetingSchema),[editing,setEditing]=useState(false),[participantPage,setParticipantPage]=useState(1),[agreementPage,setAgreementPage]=useState(1),[eventPage,setEventPage]=useState(1);
 const participants=useMeetingQuery(identity,'meetings/'+id+'/participants?page='+participantPage,participantsPageSchema,!!query.data),agreements=useMeetingQuery(identity,'meetings/'+id+'/agreements?page='+agreementPage,agreementsPageSchema,!!query.data),events=useMeetingQuery(identity,'meetings/'+id+'/events?page='+eventPage,meetingEventsPageSchema,!!query.data);
 const update=useMeetingCommand(identity,'meetings.update'),complete=useMeetingCommand(identity,'meetings.results'),row=query.data;
 return <section className="min-w-0 space-y-4 break-words"><h1 className="text-2xl font-semibold">Reunión institucional</h1><Link className="underline" to="/meetings">Volver a reuniones</Link><QueryState pending={query.isPending} error={query.isError} retry={query.refetch}/>
 {row&&<><MeetingSummary row={row}/><p>Registrada por {row.createdBy.displayName} · {new Date(row.createdAt).toLocaleString('es-BO')}</p>
 {row.meetingUrl&&<p><a className="underline break-all" href={row.meetingUrl} target="_blank" rel="noreferrer">Enlace de reunión</a></p>}{row.location&&<p>Lugar: {row.location}</p>}{row.cancellationReason&&<p>Motivo de cancelación: {row.cancellationReason}</p>}
 {row.canEdit&&identity.permissions.includes('meetings.update')&&<button className={buttonClass} onClick={()=>setEditing(!editing)}>Editar planificación futura</button>}
 {editing&&row.canEdit&&<PlanningFormView row={row} pending={update.isPending} label="Guardar planificación" submit={async body=>{await update.mutateAsync({path:'meetings/'+id,method:'PATCH',body:{...body,expectedVersion:row.version}});setEditing(false);}}/>}<MutationError error={update.error}/>
 {row.canComplete&&identity.permissions.includes('meetings.results')&&<button className={buttonClass} disabled={complete.isPending} onClick={()=>complete.mutate({path:'meetings/'+id+'/complete',body:{expectedVersion:row.version}})}>Registrar reunión realizada</button>}<MutationError error={complete.error}/>
 {row.status==='SCHEDULED'&&identity.permissions.includes('meetings.update')&&<CancelForm identity={identity} row={row}/>}
 <button className={buttonClass} onClick={()=>void query.refetch()}>Recargar reunión y revisar cambios</button>
 <section aria-label="Participantes de reunión" className="space-y-3"><h2 className="text-xl font-semibold">Participantes de reunión</h2><QueryState pending={participants.isPending} error={participants.isError} retry={participants.refetch}/>{participants.data?.total===0&&<p>No hay participantes incorporados.</p>}
 {(['internal','external']as const).map(kind=><div key={kind}><h3 className="font-semibold">{kind==='internal'?'Equipo CECASEM':'Participantes externos'}</h3><ul className="space-y-2">{participants.data?.items.filter(participant=>kind==='internal'?!!participant.userId:!participant.userId).map(participant=><ParticipantRow key={participant.id+participant.attendance} identity={identity} row={row} participant={participant}/>)}</ul></div>)}
 {participants.data&&<Pagination page={participantPage} total={participants.data.total} onPage={setParticipantPage}/>}
 {row.status!=='CANCELLED'&&identity.permissions.includes('meetings.participants')&&<ParticipantForm identity={identity} row={row}/>}</section>
 <section aria-label="Acuerdos de reunión" className="space-y-3"><h2 className="text-xl font-semibold">Acuerdos de reunión</h2><QueryState pending={agreements.isPending} error={agreements.isError} retry={agreements.refetch}/>{agreements.data?.total===0&&<p>No hay acuerdos registrados.</p>}<ol className="space-y-3">{agreements.data?.items.map(agreement=><li key={agreement.id} className="rounded border p-3"><p>{agreement.createdBy.displayName} · {new Date(agreement.createdAt).toLocaleString('es-BO')}</p><p className="whitespace-pre-wrap">{agreement.text}</p></li>)}</ol>{agreements.data&&<Pagination page={agreementPage} total={agreements.data.total} onPage={setAgreementPage}/>}
 {row.status==='COMPLETED'&&identity.permissions.includes('meetings.results')&&<AgreementForm identity={identity} row={row}/>}</section>
 <Attachments identity={identity} resource="meetings" resourceId={id} processId={row.processId??undefined} blocked={row.status==='CANCELLED'}/>
 <section aria-label="Historial de reunión" className="space-y-3"><h2 className="text-xl font-semibold">Historial de reunión</h2><QueryState pending={events.isPending} error={events.isError} retry={events.refetch}/><ol className="space-y-3">{events.data?.items.map(event=><li key={event.id} className="rounded border p-3"><p>{event.actor.displayName} · {new Date(event.createdAt).toLocaleString('es-BO')}</p><MeetingEventContent event={event}/></li>)}</ol>{events.data&&<Pagination page={eventPage} total={events.data.total} onPage={setEventPage}/>}</section></>}
 </section>;
}
function CancelForm({identity,row}:{identity:AuthIdentity;row:Meeting}){
 const form=useForm<{reason:string}>({defaultValues:{reason:''}}),mutation=useMeetingCommand(identity,'meetings.update');
 return <form aria-label="Cancelar reunión" className="space-y-2 rounded border p-3" onSubmit={form.handleSubmit(async values=>{if(!values.reason.trim()){form.setError('reason',{message:'Indica el motivo.'});return;}try{await mutation.mutateAsync({path:'meetings/'+row.id+'/cancel',body:{expectedVersion:row.version,reason:values.reason}});form.reset();}catch{/* Conserva motivo. */}})}><Field label="Motivo de cancelación" error={form.formState.errors.reason?.message}><textarea aria-label="Motivo de cancelación" className={inputClass} maxLength={5000} disabled={mutation.isPending} {...form.register('reason')}/></Field><button className={buttonClass} disabled={mutation.isPending}>Cancelar reunión conservando historial</button><MutationError error={mutation.error}/></form>;
}
function AgreementForm({identity,row}:{identity:AuthIdentity;row:Meeting}){
 const form=useForm<{text:string}>({defaultValues:{text:''}}),mutation=useMeetingCommand(identity,'meetings.results');
 return <form aria-label="Agregar acuerdo" className="space-y-2" onSubmit={form.handleSubmit(async values=>{if(!values.text.trim()){form.setError('text',{message:'Indica el acuerdo.'});return;}try{await mutation.mutateAsync({path:'meetings/'+row.id+'/agreements',body:{expectedVersion:row.version,text:values.text}});form.reset();}catch{/* Conserva texto. */}})}><p>Los acuerdos anteriores se conservan. Registra aclaraciones como hechos posteriores.</p><Field label="Nuevo acuerdo" error={form.formState.errors.text?.message}><textarea aria-label="Nuevo acuerdo" className={inputClass} maxLength={5000} disabled={mutation.isPending} {...form.register('text')}/></Field><button className={buttonClass} disabled={mutation.isPending}>Registrar acuerdo</button><MutationError error={mutation.error}/></form>;
}
