ALTER TYPE "NotificationType" ADD VALUE 'OPPORTUNITY_DISCARDED';
ALTER TYPE "NotificationType" ADD VALUE 'OPPORTUNITY_FINISHED';
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_PARTICIPANT_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'MEETING_RESCHEDULED';
