import { QueryClientProvider } from '@tanstack/react-query';
import { render,screen,waitFor,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { AppRoutes } from '../../app/router/app-routes';
import { createQueryClient } from '../../lib/query/query-client';
import type { AuthIdentity } from '../auth/session';
import { contactMethodSchema,contactCreateFormSchema,type ContactMethod,type ContactAssociation } from './contacts.contracts';
const stamp='2026-10-02T00:00:00.000Z',methodId='11111111-1111-4111-8111-111111111111',otherId='22222222-2222-4222-8222-222222222222';
const identity:AuthIdentity={id:'qa',givenNames:'QA',familyNames:'Contactos',username:'qa',email:'qa@example.test',role:'RESEARCH',permissions:['directory.read','directory.write','directory.history.read']};
const person={id:'person',displayName:'Ana QA',givenNames:null,familyNames:null,isActive:true,version:1,createdAt:stamp,updatedAt:stamp,lastVerifiedAt:null,currentRelationsCount:0};
const organization={id:'org-a',name:'Organización A',country:null,alias:null,description:null,officialWebsite:null,parentId:null,parent:null,categories:[],isActive:true,version:1,createdAt:stamp,updatedAt:stamp,lastVerifiedAt:null};
const base:ContactMethod={id:methodId,type:'EMAIL',value:'contacto@fundacion.org',label:null,condition:'USABLE',version:1,createdAt:stamp,updatedAt:stamp,associationCount:0};
const context={sourceDescription:'Sitio oficial',sourceUrl:null,notes:'Contexto original',isActive:true,version:1,createdAt:stamp,updatedAt:stamp,lastVerifiedAt:null};
const page=(items:unknown[],total=items.length)=>({items,total,page:1,pageSize:25});
describe('Medios canónicos y asociaciones en interfaz',()=>{
  let client=createQueryClient(),actor=identity,methods:ContactMethod[]=[],associations:ContactAssociation[]=[],listMode='ok',lookupMode='ok',conflicting=false,race=false,loggedOut=false;
  let releaseObsolete:((value:Response)=>void)|undefined;
  const fetchMock=vi.fn<(url:string,options?:RequestInit)=>Promise<Response>>();
  function publicMethod(id:string){const method=methods.find(row=>row.id===id)!;return {...method,associationCount:associations.filter(row=>row.contactMethodId===id).length};}
  function wire(row:ContactAssociation):ContactAssociation{return {...row,contactMethod:publicMethod(row.contactMethodId)};}
  function personAssociation(id='pc',contactId=methodId):ContactAssociation{return {id,personId:person.id,person:{id:person.id,displayName:person.displayName,isActive:true},contactMethodId:contactId,...context,contactMethod:publicMethod(contactId)};}
  function orgAssociation(id='oc',contactId=methodId):ContactAssociation{return {id,organizationId:organization.id,organization:{id:organization.id,name:organization.name,isActive:true},contactMethodId:contactId,...context,contactMethod:publicMethod(contactId)};}
  beforeEach(()=>{
    client=createQueryClient();actor={...identity};methods=[{...base},{...base,id:otherId,value:'otro@fundacion.org'}];associations=[];listMode='ok';lookupMode='ok';conflicting=false;race=false;loggedOut=false;releaseObsolete=undefined;fetchMock.mockReset();
    fetchMock.mockImplementation((url,options)=>{
      const path=url.replace('/api/v1/',''),route=path.split('?')[0]!,query=new URLSearchParams(path.split('?')[1]),method=options?.method??'GET',body=options?.body?JSON.parse(String(options.body)) as Record<string,unknown>:{};
      if (url.includes('/duplicate-candidates?')) return Promise.resolve(Response.json({items:[],total:0,page:1,pageSize:25}));
      if (route.endsWith('/verification')) return Promise.resolve(Response.json({objectType:'person',classification:'personal',intervalMonths:6,verificationStatus:'NEVER_VERIFIED',lastVerifiedAt:null,lastVerifiedBy:null,nextReviewAt:null,changedSinceVerification:false,timeReviewDue:false,version:1,contactValueVersion:null}));
      if(route==='auth/me')return Promise.resolve(Response.json(loggedOut?{}:actor,{status:loggedOut?401:200}));
      if(route==='auth/logout'){loggedOut=true;return Promise.resolve(new Response(null,{status:204}));}
      if(route==='people/person')return Promise.resolve(Response.json(person));
      if(route==='organizations/org-a')return Promise.resolve(Response.json(organization));
      if(route.includes('/history'))return Promise.resolve(Response.json({...page([{operationId:'operation-test',createdAt:stamp,objectType:'PERSON',actor:{id:identity.id,givenNames:identity.givenNames,familyNames:identity.familyNames,isActive:true},contextRecorded:true,relatedReferences:[],replacement:null,changes:[{field:'notes',label:'Observaciones',previousValue:'Anterior',newValue:'Corregido',previousReferences:[],newReferences:[],added:[],removed:[]}]}]),references:{}}));
      if(route.includes('/relations')||route.includes('/children')||route==='organizations/org-a/people')return Promise.resolve(Response.json(page([])));
      if(route==='contact-methods/email'){
        if(lookupMode==='error')return Promise.resolve(new Response(null,{status:500}));
        if(lookupMode==='slow'&&query.get('email')==='first@example.test')return new Promise<Response>(resolve=>{releaseObsolete=resolve;});
        const found=lookupMode==='missing'?null:methods.find(row=>row.type==='EMAIL'&&row.value===query.get('email'));
        return Promise.resolve(Response.json({contact:found?publicMethod(found.id):null}));
      }
      if(route==='contact-methods'){const items=methods.filter(row=>!query.get('type')||row.type===query.get('type')).map(row=>publicMethod(row.id));const currentPage=Number(query.get('page')??1);return Promise.resolve(Response.json({...page(items.slice((currentPage-1)*25,currentPage*25),items.length),page:currentPage}));}
      if(route.startsWith('contact-methods/')){
        const id=route.split('/')[1]!;
        if(route.endsWith('/people')||route.endsWith('/organizations'))return Promise.resolve(Response.json(page(associations.filter(row=>row.contactMethodId===id&&(route.endsWith('/people')?'personId' in row:'organizationId' in row)).map(wire))));
        if(method==='PUT'){
          if(conflicting||body.expectedVersion!==publicMethod(id).version)return Promise.resolve(Response.json({code:'VERSION_CONFLICT'},{status:409}));
          if(publicMethod(id).associationCount>1&&!body.confirmShared)return Promise.resolve(Response.json({code:'SHARED_CONTACT_CONFIRMATION_REQUIRED'},{status:409}));
          const existing=methods.find(row=>row.id!==id&&row.value===String(body.value).trim().toLowerCase());
          if(existing)return Promise.resolve(Response.json({code:'CONTACT_VALUE_EXISTS',details:{contactMethodId:existing.id}},{status:409}));
          methods=methods.map(row=>row.id===id?{...row,value:String(body.value).trim().toLowerCase(),label:body.label?String(body.label):null,version:row.version+1}:row);return Promise.resolve(Response.json(publicMethod(id)));
        }
        if(method==='PATCH'){methods=methods.map(row=>row.id===id?{...row,condition:body.condition==='UNUSABLE'?'UNUSABLE':'USABLE',version:row.version+1}:row);return Promise.resolve(Response.json(publicMethod(id)));}
        return Promise.resolve(Response.json(publicMethod(id)));
      }
      if(route==='people/person/contacts'||route==='organizations/org-a/contacts'||route.endsWith('/contacts/existing')){
        const fromPerson=route.startsWith('people');
        if(method==='GET'){
          if(listMode==='pending')return new Promise<Response>(()=>undefined);
          if(listMode==='error')return Promise.resolve(new Response(null,{status:500}));
          return Promise.resolve(Response.json(page(associations.filter(row=>fromPerson?'personId' in row:'organizationId' in row).map(wire))));
        }
        let id=String(body.contactMethodId??'');
        if(!route.endsWith('/existing')){
          const existing=methods.find(row=>row.type==='EMAIL'&&row.value===String(body.value).trim().toLowerCase());
          if(race||existing)return Promise.resolve(Response.json({code:'CONTACT_EMAIL_EXISTS',details:{contactMethodId:existing?.id??methodId}},{status:409}));
          id='33333333-3333-4333-8333-333333333333';methods.push(contactMethodSchema.parse({...base,id,type:body.type,value:String(body.value).trim(),label:body.label||null}));
        }
        if(conflicting)return Promise.resolve(Response.json({code:'VERSION_CONFLICT'},{status:409}));
        const existing=associations.find(row=>row.contactMethodId===id&&(fromPerson?'personId' in row:'organizationId' in row));
        if(existing)return Promise.resolve(Response.json({outcome:'existing',association:wire(existing)}));
        const row={...(fromPerson?personAssociation('new',id):orgAssociation('new',id)),sourceDescription:body.sourceDescription?String(body.sourceDescription):null,sourceUrl:body.sourceUrl?String(body.sourceUrl):null,notes:body.notes?String(body.notes):null};associations.push(row);methods=methods.map(method=>method.id===id?{...method,version:method.version+1}:method);
        return Promise.resolve(Response.json({outcome:'created',association:wire(row)},{status:route.endsWith('/existing')?200:201}));
      }
      if(route.startsWith('person-contacts/')||route.startsWith('organization-contacts/')){
        const id=route.split('/')[1]!,found=associations.find(row=>row.id===id)!;
        if(method==='GET')return Promise.resolve(Response.json(wire(found)));
        if(conflicting||body.expectedVersion!==found.version)return Promise.resolve(Response.json({code:'VERSION_CONFLICT'},{status:409}));
        if(route.endsWith('/replace')){
          const targetId=String(body.contactMethodId);const fresh={...personAssociation('replacement',targetId),notes:body.notes?String(body.notes):null,sourceDescription:body.sourceDescription?String(body.sourceDescription):null,sourceUrl:body.sourceUrl?String(body.sourceUrl):null};
          associations=associations.map(row=>row.id===id?{...row,isActive:false,version:row.version+1}:row);associations.push(fresh);return Promise.resolve(Response.json({outcome:'created',association:wire(fresh),previous:wire({...found,isActive:false})}));
        }
        associations=associations.map(row=>row.id===id?{...row,...(method==='PUT'?{sourceDescription:body.sourceDescription?String(body.sourceDescription):null,sourceUrl:body.sourceUrl?String(body.sourceUrl):null,notes:body.notes?String(body.notes):null}:{isActive:route.endsWith('/status')?body.isActive===true:false}),version:row.version+1}:row);
        return Promise.resolve(Response.json(wire(associations.find(row=>row.id===id)!)));
      }
      return Promise.reject(new Error('Ruta inesperada: '+path));
    });vi.stubGlobal('fetch',fetchMock);
  });
  afterEach(()=>{client.clear();vi.unstubAllGlobals();});
  function app(path='/people/person'){return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AppRoutes/></MemoryRouter></QueryClientProvider>);}
  async function register(){const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Registrar medio de contacto'}));return user;}
  it('muestra vacío y no simula verificación',async()=>{app();expect(await screen.findByText('No hay medios de contacto asociados.')).toBeVisible();expect(screen.queryByRole('button',{name:/verificar/i})).not.toBeInTheDocument();});
  it.each(['pending','error'])('lista maneja %s y permite reintentar',async mode=>{listMode=mode;app();const section=(await screen.findByRole('heading',{name:'Medios de contacto'})).closest('section')!;
    if(mode==='pending')expect(await within(section).findByText('Cargando…')).toBeVisible();else{expect(await within(section).findByRole('alert')).toBeVisible();listMode='ok';await userEvent.setup().click(within(section).getByRole('button',{name:'Reintentar'}));expect(await screen.findByText('No hay medios de contacto asociados.')).toBeVisible();}});
  it('registra medio y asociación juntos e invalida caché de identidad',async()=>{const invalidate=vi.spyOn(client,'invalidateQueries');app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'nuevo@example.test');await user.type(screen.getByLabelText('Descripción de fuente (opcional)'),'Documento');await user.click(screen.getByRole('button',{name:'Registrar medio y asociar'}));
    expect(await screen.findByRole('link',{name:'nuevo@example.test'})).toBeVisible();expect(invalidate).toHaveBeenCalledWith({queryKey:['directory','qa']});const call=fetchMock.mock.calls.find(([,options])=>options?.method==='POST');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({type:'EMAIL',value:'nuevo@example.test',sourceDescription:'Documento'});});
  it('ofrece los seis tipos y exige descripción para OTHER',async()=>{app();const user=await register();expect(within(screen.getByLabelText('Tipo de medio')).getAllByRole('option')).toHaveLength(6);await user.selectOptions(screen.getByLabelText('Tipo de medio'),'OTHER');await user.type(screen.getByLabelText('Valor del medio'),'Canal público');await user.click(screen.getByRole('button',{name:'Registrar medio y asociar'}));expect(await screen.findByText('Describe qué canal representa este medio.')).toBeVisible();expect(fetchMock.mock.calls.some(([,options])=>options?.method==='POST')).toBe(false);});
  it('correo existente muestra organización, conserva formulario y espera confirmación',async()=>{associations=[orgAssociation()];app();const user=await register();await user.type(screen.getByLabelText('Descripción de fuente (opcional)'),'Fuente personal');await user.type(screen.getByLabelText('Observaciones de la asociación (opcional)'),'Mi observación');await user.type(screen.getByLabelText('Valor del medio'),' CONTACTO@FUNDACION.ORG ');
    expect(await screen.findByText('Este correo ya está registrado.')).toBeVisible();expect(await screen.findByRole('link',{name:'Organización A'})).toBeVisible();expect(screen.getByRole('link',{name:'Ver ficha del medio existente'})).toBeVisible();expect(fetchMock.mock.calls.some(([,options])=>options?.method==='POST')).toBe(false);expect(screen.getByLabelText('Observaciones de la asociación (opcional)')).toHaveValue('Mi observación');
    await user.click(screen.getByRole('button',{name:'Asociar este contacto'}));await screen.findByText('Fuente: Fuente personal');expect(associations).toHaveLength(2);expect(associations[0]!.notes).toBe('Contexto original');const call=fetchMock.mock.calls.find(([url,options])=>url.endsWith('/contacts/existing')&&options?.method==='POST');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({contactMethodId:methodId,sourceDescription:'Fuente personal',notes:'Mi observación'});});
  it('consulta email con debounce: no envía una solicitud por tecla',async()=>{app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'contacto@fundacion.org');await screen.findByText('Este correo ya está registrado.');expect(fetchMock.mock.calls.filter(([url])=>url.includes('contact-methods/email?'))).toHaveLength(1);});
  it('cancela consulta obsoleta y no muestra su resultado tardío',async()=>{lookupMode='slow';app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'first@example.test');await waitFor(()=>expect(releaseObsolete).toBeDefined());const oldCall=fetchMock.mock.calls.find(([url])=>url.includes('first%40example.test'))!;
    await user.clear(screen.getByLabelText('Valor del medio'));await user.type(screen.getByLabelText('Valor del medio'),'second@example.test');await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>url.includes('second%40example.test'))).toBe(true));expect(oldCall[1]?.signal?.aborted).toBe(true);releaseObsolete!(Response.json({contact:publicMethod(methodId)}));await waitFor(()=>expect(screen.queryByText('Este correo ya está registrado.')).not.toBeInTheDocument());expect(screen.getByLabelText('Valor del medio')).toHaveValue('second@example.test');});
  it('carrera al guardar ofrece reutilización con contexto sin asociar automáticamente',async()=>{lookupMode='missing';race=true;associations=[orgAssociation()];app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'contacto@fundacion.org');await user.type(screen.getByLabelText('Observaciones de la asociación (opcional)'),'Borrador conservado');await user.click(screen.getByRole('button',{name:'Registrar medio y asociar'}));await screen.findByText('Este correo ya está registrado.');expect(screen.getByLabelText('Observaciones de la asociación (opcional)')).toHaveValue('Borrador conservado');expect(fetchMock.mock.calls.filter(([,options])=>options?.method==='POST')).toHaveLength(1);await user.click(screen.getByRole('button',{name:'Asociar este contacto'}));expect(await screen.findByText('Observaciones: Borrador conservado')).toBeVisible();});
  it('selecciona un PHONE existente sin imponer unicidad de correo',async()=>{const phone={...base,id:'44444444-4444-4444-8444-444444444444',type:'PHONE' as const,value:'+591 1234567'};methods.push(phone);app();const user=await register();await user.selectOptions(screen.getByLabelText('Tipo de medio'),'PHONE');await user.click(screen.getByRole('button',{name:'Seleccionar un medio existente'}));await user.click(await screen.findByRole('button',{name:'Seleccionar +591 1234567'}));expect(await screen.findByText('Este medio ya está registrado.')).toBeVisible();await user.click(screen.getByRole('button',{name:'Asociar este contacto'}));expect(await screen.findByRole('link',{name:'+591 1234567'})).toBeVisible();expect(fetchMock.mock.calls.some(([url])=>url.includes('contact-methods/email?'))).toBe(false);});
  it('paginar el selector con un formulario válido no crea ni asocia automáticamente',async()=>{methods=Array.from({length:26},(_,index)=>({...base,id:'fixture-'+index,value:'contacto'+index+'@example.test'}));app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'nuevo@example.test');await user.click(screen.getByRole('button',{name:'Seleccionar un medio existente'}));const selector=(await screen.findByText('Medios canónicos del tipo seleccionado, incluidos sus antecedentes.')).closest('section')!;await user.click(within(selector).getByRole('button',{name:'Siguiente'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>url.includes('contact-methods?type=EMAIL&page=2'))).toBe(true));expect(fetchMock.mock.calls.some(([,options])=>options?.method==='POST')).toBe(false);});
  it('editar contexto de persona no cambia asociación de organización',async()=>{associations=[personAssociation(),orgAssociation()];app();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Editar contexto'}));await user.clear(screen.getByLabelText('Observaciones de la asociación (opcional)'));await user.type(screen.getByLabelText('Observaciones de la asociación (opcional)'),'Nota personal');await user.click(screen.getByRole('button',{name:'Guardar contexto'}));expect(await screen.findByText('Observaciones: Nota personal')).toBeVisible();expect(associations.find(row=>'organizationId' in row)?.notes).toBe('Contexto original');});
  it('historial muestra valores anteriores/nuevos y autor de asociación',async()=>{associations=[personAssociation()];app();await userEvent.setup().click(await screen.findByRole('button',{name:'Ver historial de asociación'}));const card=(screen.getByRole('link',{name:'contacto@fundacion.org'})).closest('li')!;expect(await within(card).findByText('Antes: Anterior')).toBeVisible();expect(within(card).getByText('Después: Corregido')).toBeVisible();expect(within(card).getByText(/QA Contactos/)).toBeVisible();});
  it('finalización pide confirmación y conserva medio y asociación como antecedente',async()=>{associations=[personAssociation()];app();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Finalizar asociación'}));expect(screen.getByRole('button',{name:'Confirmar finalización de asociación'})).toBeDisabled();await user.click(screen.getByRole('checkbox',{name:'Confirmo finalizar esta asociación'}));await user.click(screen.getByRole('button',{name:'Confirmar finalización de asociación'}));expect(await screen.findByText('Asociación inactiva / antecedente · Medio: Disponible')).toBeVisible();expect(methods.find(row=>row.id===methodId)).toBeDefined();expect(associations).toHaveLength(1);});
  it('conflicto de contexto conserva borrador y recarga solo por decisión explícita',async()=>{associations=[personAssociation()];conflicting=true;app();const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Editar contexto'}));await user.clear(screen.getByLabelText('Observaciones de la asociación (opcional)'));await user.type(screen.getByLabelText('Observaciones de la asociación (opcional)'),'Mi borrador');associations=associations.map(row=>({...row,notes:'Cambio ajeno',version:2}));await user.click(screen.getByRole('button',{name:'Guardar contexto'}));expect(await screen.findByRole('alert')).toHaveTextContent('Recargar descartará');expect(screen.getByLabelText('Observaciones de la asociación (opcional)')).toHaveValue('Mi borrador');expect(fetchMock.mock.calls.filter(([,options])=>options?.method==='PUT')).toHaveLength(1);await user.click(screen.getByRole('button',{name:'Recargar ficha y descartar cambios'}));await waitFor(()=>expect(screen.getByLabelText('Observaciones de la asociación (opcional)')).toHaveValue('Cambio ajeno'));});
  it('medio compartido muestra afectados y exige confirmación para corrección global',async()=>{associations=[personAssociation(),orgAssociation()];app('/contact-methods/'+methodId);const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Corregir medio de contacto'}));await user.clear(screen.getByLabelText('Valor corregido del medio'));await user.type(screen.getByLabelText('Valor corregido del medio'),'corregido@fundacion.org');await user.click(screen.getByRole('button',{name:'Guardar corrección del medio'}));expect(await screen.findByRole('alert')).toHaveTextContent('Confirma la corrección global');expect(screen.getByRole('link',{name:'Ana QA'})).toBeVisible();expect(screen.getByRole('link',{name:'Organización A'})).toBeVisible();await user.click(screen.getByRole('checkbox',{name:'Confirmo la corrección global del medio compartido'}));await user.click(screen.getByRole('button',{name:'Guardar corrección del medio'}));expect(await screen.findByRole('heading',{name:'Medio de contacto: corregido@fundacion.org'})).toBeVisible();expect(associations).toHaveLength(2);});
  it('corregir hacia correo existente permite sustituir solo la asociación elegida',async()=>{associations=[personAssociation(),orgAssociation()];app('/contact-methods/'+methodId);const user=userEvent.setup();await user.click(await screen.findByRole('button',{name:'Corregir medio de contacto'}));await user.clear(screen.getByLabelText('Valor corregido del medio'));await user.type(screen.getByLabelText('Valor corregido del medio'),'otro@fundacion.org');await user.click(screen.getByRole('checkbox',{name:'Confirmo la corrección global del medio compartido'}));await user.click(screen.getByRole('button',{name:'Guardar corrección del medio'}));await screen.findByRole('link',{name:'Ver ficha del correo existente'});expect(methods[0]!.value).toBe('contacto@fundacion.org');expect(fetchMock.mock.calls.some(([,options])=>options?.method==='POST')).toBe(false);
    await user.click(screen.getByRole('button',{name:'Usar el medio existente para Ana QA'}));await user.click(screen.getByRole('checkbox',{name:'Confirmo sustituir esta asociación conservando el antecedente'}));await user.click(screen.getByRole('button',{name:'Confirmar sustitución'}));await waitFor(()=>expect(associations).toHaveLength(3));expect(associations.find(row=>row.id==='pc')?.isActive).toBe(false);expect(associations.find(row=>row.id==='oc')?.isActive).toBe(true);expect(associations.find(row=>row.id==='replacement')?.contactMethodId).toBe(otherId);});
  it('medio no utilizable conserva contexto pero no ofrece asociación activa',async()=>{methods[0] = {...methods[0]!,condition:'UNUSABLE'};app();const user=await register();await user.type(screen.getByLabelText('Valor del medio'),'contacto@fundacion.org');await screen.findByText('Este correo ya está registrado.');expect(screen.getByRole('button',{name:'Asociar este contacto'})).toBeDisabled();expect(screen.getByText(/No utilizable \(reportado\)/)).toBeVisible();});
  it('operador no cambia condición global ni reactiva antecedentes',async()=>{associations=[{...personAssociation(),isActive:false}];app('/contact-methods/'+methodId);await screen.findByRole('heading',{name:'Medio de contacto: contacto@fundacion.org'});expect(screen.queryByRole('button',{name:'Marcar medio no utilizable'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Reactivar asociación'})).not.toBeInTheDocument();});
  it('Admin dispone de controles administrativos',async()=>{actor={...identity,role:'ADMINISTRATOR',permissions:[...identity.permissions,'directory.status.update']};associations=[{...personAssociation(),isActive:false}];app('/contact-methods/'+methodId);expect(await screen.findByRole('button',{name:'Marcar medio no utilizable'})).toBeVisible();expect(await screen.findByRole('button',{name:'Reactivar asociación'})).toBeVisible();});
  it('logout limpia medios y asociaciones de la caché',async()=>{associations=[personAssociation()];app();await screen.findByRole('link',{name:'contacto@fundacion.org'});expect(client.getQueriesData({queryKey:['directory','qa']}).length).toBeGreaterThan(1);await userEvent.setup().click(screen.getByRole('button',{name:'Cerrar sesión'}));await screen.findByRole('heading',{name:'Iniciar sesión'});expect(client.getQueriesData({queryKey:['directory']})).toHaveLength(0);});
  it('validación preserva email con + y rechaza URL peligrosa/teléfono inválido',()=>{const input={type:'EMAIL',value:'Nombre.Apellido+Proyecto@example.test',label:'',sourceDescription:'',sourceUrl:'',notes:''};expect(contactCreateFormSchema.safeParse(input).success).toBe(true);expect(contactCreateFormSchema.safeParse({...input,type:'WEB',value:'javascript:x'}).success).toBe(false);expect(contactCreateFormSchema.safeParse({...input,type:'PHONE',value:'abc'}).success).toBe(false);expect(contactCreateFormSchema.safeParse({...input,type:'LINKEDIN',value:''}).success).toBe(false);});
});
