ALTER TYPE "AuditAction" ADD VALUE 'PROCESS_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'PROCESS_STATE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'PROCESS_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE 'PROCESS_REOPENED';
