import { UserRole } from '../../../generated/prisma/client';
import { isPermission, PERMISSIONS, type Permission } from './permission';

const DIRECTORY_PERMISSIONS = [PERMISSIONS.DIRECTORY_READ, PERMISSIONS.DIRECTORY_WRITE, PERMISSIONS.DIRECTORY_HISTORY_READ, PERMISSIONS.DIRECTORY_VERIFY, PERMISSIONS.DIRECTORY_DUPLICATES_DISMISS] as const;

const INTENT_PERMISSIONS = [PERMISSIONS.INTENT_READ, PERMISSIONS.INTENT_CREATE, PERMISSIONS.INTENT_CANCEL, PERMISSIONS.INTENT_CONVERT] as const;
const COMMUNICATION_PERMISSIONS = [PERMISSIONS.COMMUNICATION_READ, PERMISSIONS.SENT_COMMUNICATION_CREATE, PERMISSIONS.RECEIVED_COMMUNICATION_CREATE, PERMISSIONS.COMMUNICATION_AMEND, PERMISSIONS.COMMUNICATION_INVALIDATE] as const;
const RESTRICTION_PERMISSIONS = [PERMISSIONS.RESTRICTION_READ, PERMISSIONS.RESTRICTION_CREATE] as const;
const PROCESS_PERMISSIONS = [PERMISSIONS.PROCESS_READ, PERMISSIONS.PROCESS_CREATE, PERMISSIONS.PROCESS_STATE_CHANGE, PERMISSIONS.PROCESS_CLOSE, PERMISSIONS.PROCESS_REOPEN, PERMISSIONS.INTERNAL_NOTE_CREATE] as const;
const ROLE_PERMISSIONS: Readonly<Record<UserRole, readonly Permission[]>> = Object.freeze({
  [UserRole.ADMINISTRATOR]: Object.freeze([PERMISSIONS.FIRST_ACCESS_ISSUE, PERMISSIONS.PASSWORD_RESET_ISSUE,
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_DEACTIVATED_READ, PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_ROLE_UPDATE, PERMISSIONS.USERS_STATUS_UPDATE, PERMISSIONS.USERS_MAILBOXES_MANAGE,
    ...DIRECTORY_PERMISSIONS, PERMISSIONS.DIRECTORY_STATUS_UPDATE, PERMISSIONS.SETTINGS_VERIFICATION_UPDATE, PERMISSIONS.DIRECTORY_DUPLICATES_MANAGE, ...INTENT_PERMISSIONS, ...PROCESS_PERMISSIONS, ...RESTRICTION_PERMISSIONS, ...COMMUNICATION_PERMISSIONS, PERMISSIONS.RESTRICTION_LIFT]),
  [UserRole.BOARD]: Object.freeze([PERMISSIONS.USERS_READ, ...DIRECTORY_PERMISSIONS, ...INTENT_PERMISSIONS, ...PROCESS_PERMISSIONS, ...RESTRICTION_PERMISSIONS, ...COMMUNICATION_PERMISSIONS, PERMISSIONS.RESTRICTION_LIFT]),
  [UserRole.RESEARCH]: Object.freeze([...DIRECTORY_PERMISSIONS, ...INTENT_PERMISSIONS, ...PROCESS_PERMISSIONS, ...RESTRICTION_PERMISSIONS, ...COMMUNICATION_PERMISSIONS]),
  [UserRole.PLANNING]: Object.freeze([...DIRECTORY_PERMISSIONS, ...INTENT_PERMISSIONS, ...PROCESS_PERMISSIONS, ...RESTRICTION_PERMISSIONS, ...COMMUNICATION_PERMISSIONS]),
});
const NO_PERMISSIONS: readonly Permission[] = Object.freeze([]);

export function getRolePermissions(role: string): readonly Permission[] {
  return Object.hasOwn(ROLE_PERMISSIONS, role) ? Object.freeze([...ROLE_PERMISSIONS[role as UserRole], PERMISSIONS.FILE_READ, PERMISSIONS.FILE_UPLOAD, PERMISSIONS.OPPORTUNITY_READ, PERMISSIONS.OPPORTUNITY_CREATE, PERMISSIONS.OPPORTUNITY_UPDATE, PERMISSIONS.OPPORTUNITY_STATE_CHANGE, PERMISSIONS.OPPORTUNITY_DISCARD, PERMISSIONS.OPPORTUNITY_FINISH]) : NO_PERMISSIONS;
}

export function hasPermission(role: string, permission: string): boolean {
  return hasAllPermissions(getRolePermissions(role), [permission]);
}

export function hasAllPermissions(granted: readonly Permission[], required: readonly string[]): boolean {
  return required.length > 0 && Array.from(required).every(permission => isPermission(permission) && granted.includes(permission));
}
