export type DirectoryErrorCode = 'FORBIDDEN' | 'INVALID_DIRECTORY' | 'ORGANIZATION_NOT_FOUND' | 'PERSON_NOT_FOUND' | 'PERSON_RELATION_NOT_FOUND' | 'CATEGORY_NOT_FOUND' | 'CATEGORY_EXISTS' | 'CATEGORY_INACTIVE' | 'INVALID_HIERARCHY' | 'VERSION_CONFLICT' | 'CONTACT_METHOD_NOT_FOUND' | 'CONTACT_ASSOCIATION_NOT_FOUND' | 'CONTACT_EMAIL_EXISTS' | 'CONTACT_VALUE_EXISTS' | 'SHARED_CONTACT_CONFIRMATION_REQUIRED' | 'CONTACT_UNUSABLE' | 'INVALID_CONTACT_REPLACEMENT';
export class DirectoryError extends Error {
  constructor(public readonly code: DirectoryErrorCode, public readonly details?: { contactMethodId: string }) { super(code); }
}
