import { Test } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import type { INestApplication } from '@nestjs/common';
import type { Server } from 'node:http';
import { randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import request from 'supertest';
import { AppModule } from '../src/app.module';
import { configureApplication } from '../src/config/application';
import { validateEnvironment } from '../src/config/environment';
import { validateDatabaseUrl } from '../src/config/database-url';
import { PrismaService } from '../src/database/prisma.service';
import { UserRole } from '../src/generated/prisma/client';
import { UsersService } from '../src/modules/users/users.service';
import { SessionsService } from '../src/modules/auth/sessions.service';
import { RelationshipProcessesService } from '../src/modules/relationships/relationship-processes.service';
import { CommunicationsService } from '../src/modules/communications/communications.service';
import { OpportunitiesService } from '../src/modules/opportunities/opportunities.service';
import { AuditService } from '../src/modules/audit/audit.service';
import type { OpportunityDto, OpportunityHistoryPageDto, OpportunityPageDto } from '../src/modules/opportunities/opportunity.dto';
import type { FileMetadataDto } from '../src/modules/files/files.dto';
const databaseUrl = validateDatabaseUrl(process.env.DATABASE_URL);
if (!new URL(databaseUrl).pathname.endsWith('_test'))
  throw new Error('Oportunidades requieren base aislada _test.');
describe('Oportunidades PostgreSQL/HTTP', () => {
  let app: INestApplication<Server>, prisma: PrismaService, service: OpportunitiesService, root: string;
  const userIds: string[] = [], orgIds: string[] = [];
  beforeAll(async () => { root = await mkdtemp(join(tmpdir(), 'cecasem-opportunities-')); const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider(ConfigService).useValue(new ConfigService(validateEnvironment({ NODE_ENV: 'test', DATABASE_URL: databaseUrl, FILE_STORAGE_ROOT: root }))).compile(); app = module.createNestApplication<INestApplication<Server>>(); configureApplication(app); await app.init(); prisma = app.get(PrismaService); service = app.get(OpportunitiesService); });
  afterEach(async () => {
    jest.restoreAllMocks();
    await prisma.$transaction([
      prisma.auditEvent.deleteMany({ where: { actorUserId: { in: userIds } } }), prisma.fileAttachment.deleteMany({ where: { upload: { uploadedByUserId: { in: userIds } } } }), prisma.fileUpload.deleteMany({ where: { uploadedByUserId: { in: userIds } } }), prisma.opportunityEvent.deleteMany({ where: { actorUserId: { in: userIds } } }), prisma.opportunityOrganization.deleteMany({ where: { opportunity: { createdByUserId: { in: userIds } } } }), prisma.opportunity.deleteMany({ where: { createdByUserId: { in: userIds } } }), prisma.communicationRecipient.deleteMany({ where: { communication: { registeredByUserId: { in: userIds } } } }), prisma.communication.deleteMany({ where: { registeredByUserId: { in: userIds } } }), prisma.relationshipProcessEvent.deleteMany({ where: { actorUserId: { in: userIds } } }), prisma.processParticipant.deleteMany({ where: { userId: { in: userIds } } }), prisma.relationshipProcess.deleteMany({ where: { createdByUserId: { in: userIds } } }), prisma.organization.deleteMany({ where: { id: { in: orgIds } } }), prisma.userSession.deleteMany({ where: { userId: { in: userIds } } }), prisma.user.deleteMany({ where: { id: { in: userIds } } })
    ]);
    userIds.length = orgIds.length = 0;
  });
  afterAll(async () => { await app.close(); await rm(root, { recursive: true, force: true }); });
  async function actor(role: UserRole = UserRole.ADMINISTRATOR) { const user = await app.get(UsersService).createIdentity({ givenNames: 'QA', familyNames: 'Opportunities', email: randomUUID() + '@example.test', role }); userIds.push(user.id); const token = await prisma.$transaction(tx => app.get(SessionsService).create(user.id, tx)); return { ...user, cookie: 'cecasem_session=' + token }; }
  async function org() { const row = await prisma.organization.create({ data: { name: 'Organización ' + randomUUID() } }); orgIds.push(row.id); return row; }
  function post(cookie: string, body: object, key = randomUUID()) { return request(app.getHttpServer()).post('/api/v1/opportunities').set('Cookie', cookie).set('Idempotency-Key', key).send(body); }
  function state(cookie: string, id: string, expectedVersion: number, status: string, finalResult?: string) { return request(app.getHttpServer()).post('/api/v1/opportunities/' + id + '/state').set('Cookie', cookie).send({ expectedVersion, status, ...(finalResult ? { finalResult } : {}) }); }
  async function create(owner: Awaited<ReturnType<typeof actor>>) { const organization = await org(); return service.create({ name: 'Cooperación', organizationIds: [organization.id] }, owner.id, randomUUID()); }
  it.each(Object.values(UserRole))('%s crea, lee, edita y descarta oportunidades de otro usuario', async (role) => { const owner = await actor(), other = await actor(role), organization = await org(); const a = await post(owner.cookie, { name: 'Beca', organizationIds: [organization.id] }).expect(201), row = a.body as OpportunityDto; await request(app.getHttpServer()).get('/api/v1/opportunities/' + row.id).set('Cookie', other.cookie).expect(200); await request(app.getHttpServer()).patch('/api/v1/opportunities/' + row.id).set('Cookie', other.cookie).send({ name: 'Corrección', expectedVersion: 1 }).expect(200); await request(app.getHttpServer()).post('/api/v1/opportunities/' + row.id + '/discard').set('Cookie', other.cookie).send({ reason: 'No cumple los requisitos', expectedVersion: 2 }).expect(201); expect(await prisma.opportunityEvent.count({ where: { opportunityId: row.id } })).toBe(3); expect(await prisma.auditEvent.count({ where: { opportunityEvent: { opportunityId: row.id } } })).toBe(3); });
  it('bloquea anónimo, sesión revocada y servicio con actor inactivo', async () => { await request(app.getHttpServer()).get('/api/v1/opportunities').expect(401); const owner = await actor(), row = await create(owner); await prisma.user.update({ where: { id: owner.id }, data: { isActive: false, deactivatedAt: new Date() } }); await request(app.getHttpServer()).get('/api/v1/opportunities/' + row.id).set('Cookie', owner.cookie).expect(401); await expect(service.get(row.id, owner.id)).rejects.toMatchObject({ code: 'FORBIDDEN' }); await expect(service.update(row.id, { name: 'No', expectedVersion: 1 }, owner.id)).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('creación concurrente es idempotente y otra carga con misma clave da 409', async () => { const owner = await actor(), a = await org(), b = await org(), key = randomUUID(), body = { name: ' Beca ', organizationIds: [a.id, b.id], deadline: '2026-12-31' }; const [one, two] = await Promise.all([post(owner.cookie, body, key), post(owner.cookie, { ...body, name: 'Beca', organizationIds: [b.id, a.id] }, key)]); expect(one.status).toBe(201); expect(two.status).toBe(201); expect(one.body).toEqual(two.body); const row = one.body as OpportunityDto; expect(row.deadline).toBe('2026-12-31'); expect(await prisma.opportunity.count({ where: { createdByUserId: owner.id } })).toBe(1); await post(owner.cookie, { ...body, name: 'Otra' }, key).expect(409); expect(await prisma.opportunityEvent.count({ where: { opportunityId: row.id } })).toBe(1); });
  it('dos oportunidades distintas pueden provenir de la misma comunicación sin tocar originales ni participantes', async () => { const owner = await actor(), other = await actor(UserRole.PLANNING), organization = await org(), process = await app.get(RelationshipProcessesService).create({ organizationId: organization.id, purpose: 'Objetivo original' }, owner.id), comm = await app.get(CommunicationsService).registerReceived(process.id, { sender: 'partner@example.test', to: ['cecasem@example.test'], cc: [], bcc: [], subject: 'Dos convocatorias', body: 'Original', receivedAt: '2000-01-01T12:00:00.000Z' }, owner.id, randomUUID()); const before = await prisma.relationshipProcess.findUnique({ where: { id: process.id } }), original = await prisma.communication.findUnique({ where: { id: comm.id } }); for (const name of ['A', 'B'])
    await post(other.cookie, { name, organizationIds: [organization.id], processId: process.id, communicationId: comm.id }).expect(201); expect(await prisma.opportunity.count({ where: { communicationId: comm.id } })).toBe(2); expect(await prisma.relationshipProcess.findUnique({ where: { id: process.id } })).toEqual(before); expect(await prisma.communication.findUnique({ where: { id: comm.id } })).toEqual(original); expect(await prisma.processParticipant.count({ where: { processId: process.id, userId: other.id } })).toBe(0); });
  it('rechaza origen incoherente, inexistente y edición de origen por HTTP y SQL', async () => { const owner = await actor(), organization = await org(), p = await app.get(RelationshipProcessesService).create({ organizationId: organization.id, purpose: 'Uno' }, owner.id), p2 = await app.get(RelationshipProcessesService).create({ organizationId: organization.id, purpose: 'Dos' }, owner.id), comm = await app.get(CommunicationsService).registerReceived(p.id, { sender: 'actor@example.test', to: ['cecasem@example.test'], cc: [], bcc: [], subject: 'Beca', body: 'Original', receivedAt: '2000-01-01T12:00:00.000Z' }, owner.id, randomUUID()); await post(owner.cookie, { name: 'Inválida', organizationIds: [organization.id], processId: p2.id, communicationId: comm.id }).expect(400); await post(owner.cookie, { name: 'No existe', organizationIds: [organization.id], processId: randomUUID() }).expect(400); await expect(prisma.opportunity.create({ data: { name: 'Origen SQL incoherente', createdByUserId: owner.id, requestKey: randomUUID(), requestFingerprint: 'a'.repeat(64), processId: p2.id, communicationId: comm.id } })).rejects.toThrow(); const row = await create(owner); await request(app.getHttpServer()).patch('/api/v1/opportunities/' + row.id).set('Cookie', owner.cookie).send({ expectedVersion: 1, processId: p.id }).expect(400); await expect(prisma.opportunity.update({ where: { id: row.id }, data: { processId: p.id } })).rejects.toThrow(); });
  it('SQL impone FK/M:N únicos, origen coherente, versión y motivo significativo', async () => { const owner = await actor(), row = await create(owner); await expect(prisma.opportunityOrganization.create({ data: { opportunityId: row.id, organizationId: row.organizations[0].id } })).rejects.toThrow(); await expect(prisma.opportunityOrganization.create({ data: { opportunityId: row.id, organizationId: randomUUID() } })).rejects.toThrow(); await expect(prisma.opportunity.update({ where: { id: row.id }, data: { version: 0 } })).rejects.toThrow(); await expect(prisma.opportunity.update({ where: { id: row.id }, data: { status: 'DISCARDED', discardReason: '   ' } })).rejects.toThrow(); await expect(prisma.opportunity.update({ where: { id: row.id }, data: { status: 'FINISHED' } })).rejects.toThrow(); });
  it('edición M:N preserva anteriores/nuevos, retiene inactivas existentes y rechaza nuevas inactivas o repetidas', async () => { const owner = await actor(), row = await create(owner), a = await org(), b = await org(); await prisma.organization.update({ where: { id: row.organizations[0].id }, data: { isActive: false } }); await service.update(row.id, { name: 'Corregida', organizationIds: [row.organizations[0].id, a.id], expectedVersion: 1 }, owner.id); const event = await prisma.opportunityEvent.findFirstOrThrow({ where: { opportunityId: row.id, type: 'UPDATED' } }); expect(event.changes).toMatchObject({ name: { previous: 'Cooperación', next: 'Corregida' }, organizationIds: { previous: [row.organizations[0].id], next: [row.organizations[0].id, a.id].sort() } }); await prisma.organization.update({ where: { id: b.id }, data: { isActive: false } }); await expect(service.update(row.id, { organizationIds: [b.id], expectedVersion: 2 }, owner.id)).rejects.toMatchObject({ code: 'OPPORTUNITY_ORGANIZATION_UNAVAILABLE' }); await expect(service.update(row.id, { organizationIds: [a.id, a.id], expectedVersion: 2 }, owner.id)).rejects.toMatchObject({ code: 'INVALID_OPPORTUNITY' }); expect((await service.get(row.id, owner.id)).version).toBe(2); });
  it('dos cambios concurrentes y descarte contra edición no sobrescriben la versión', async () => { const owner = await actor(), other = await actor(UserRole.RESEARCH), row = await create(owner); const responses = await Promise.all([state(owner.cookie, row.id, 1, 'PREPARING'), request(app.getHttpServer()).post('/api/v1/opportunities/' + row.id + '/discard').set('Cookie', other.cookie).send({ expectedVersion: 1, reason: 'Otra decisión' })]); expect(responses.map(r => r.status).sort()).toEqual([201, 409]); expect(await prisma.opportunityEvent.count({ where: { opportunityId: row.id } })).toBe(2); const row2 = await create(owner); const results = await Promise.allSettled([service.discard(row2.id, { expectedVersion: 1, reason: 'Incompatible' }, owner.id), service.update(row2.id, { expectedVersion: 1, name: 'Corregida' }, other.id)]); expect(results.filter(r => r.status === 'fulfilled')).toHaveLength(1); expect(results.filter(r => r.status === 'rejected')).toHaveLength(1); });
  it('ciclo completo conserva resultado y no permite retroceso, descarte de postulada ni reapertura', async () => { const owner = await actor(), row = await create(owner); await state(owner.cookie, row.id, 1, 'SUBMITTED').expect(409); await state(owner.cookie, row.id, 1, 'PREPARING').expect(201); await state(owner.cookie, row.id, 2, 'SUBMITTED').expect(201); await expect(service.discard(row.id, { expectedVersion: 3, reason: 'No' }, owner.id)).rejects.toMatchObject({ code: 'INVALID_OPPORTUNITY_TRANSITION' }); await state(owner.cookie, row.id, 3, 'FINISHED', 'Proyecto aceptado').expect(201); await state(owner.cookie, row.id, 4, 'PREPARING').expect(409); const current = await service.get(row.id, owner.id); expect(current.finalResult).toBe('Proyecto aceptado'); expect(current.allowedStatuses).toEqual([]); });
  it('fallo de auditoría revierte creación, cambios descriptivos y asociaciones', async () => { const owner = await actor(), row = await create(owner), a = await org(); jest.spyOn(app.get(AuditService), 'recordOpportunity').mockRejectedValue(new Error('Fallo controlado')); await expect(service.create({ name: 'Revertida', organizationIds: [a.id] }, owner.id, randomUUID())).rejects.toThrow(); await expect(service.update(row.id, { name: 'No persiste', organizationIds: [a.id], expectedVersion: 1 }, owner.id)).rejects.toThrow(); expect(await prisma.opportunity.count({ where: { createdByUserId: owner.id } })).toBe(1); expect((await service.get(row.id, owner.id)).organizations[0].id).toBe(row.organizations[0].id); expect((await service.get(row.id, owner.id)).version).toBe(1); });
  it('historial y auditoría no admiten sobrescritura ni actor incoherente', async () => { const owner = await actor(), other = await actor(), row = await create(owner), event = await prisma.opportunityEvent.findFirstOrThrow({ where: { opportunityId: row.id } }); await expect(prisma.opportunityEvent.update({ where: { id: event.id }, data: { changes: { modified: true } } })).rejects.toThrow(); await expect(prisma.auditEvent.updateMany({ where: { opportunityEventId: event.id }, data: { actorUserId: other.id } })).rejects.toThrow(); });
  it('lista filtra estado/organización y pagina orden estable sin duplicados', async () => { const owner = await actor(), row = await create(owner); await create(owner); const response = await request(app.getHttpServer()).get('/api/v1/opportunities?pageSize=1&organizationId=' + row.organizations[0].id + '&status=PENDING_REVIEW').set('Cookie', owner.cookie).expect(200); expect((response.body as OpportunityPageDto).items.map(item => item.id)).toEqual([row.id]); expect((response.body as OpportunityPageDto).total).toBe(1); await request(app.getHttpServer()).get('/api/v1/opportunities?pageSize=101').set('Cookie', owner.cookie).expect(400); });
  it('adjuntos idempotentes: historial, descarga posterior al descarte y rechazo de nuevas cargas', async () => { const owner = await actor(), row = await create(owner), key = randomUUID(); const upload = (requestKey = key) => request(app.getHttpServer()).post('/api/v1/opportunities/' + row.id + '/attachments').set('Cookie', owner.cookie).set('Idempotency-Key', requestKey).attach('files', Buffer.from('Documento privado'), { filename: 'privado.txt', contentType: 'text/plain' }); const [a, b] = await Promise.all([upload(), upload()]); expect(a.status).toBe(201); expect(b.body).toEqual(a.body); const file = (a.body as FileMetadataDto[])[0]; expect(file.opportunityId).toBe(row.id); expect(file.processId).toBeNull(); expect(file.incorporation).toBe('OPPORTUNITY_ATTACHMENT'); await service.discard(row.id, { expectedVersion: 1, reason: 'No cumple' }, owner.id); await upload(randomUUID()).expect(409); await upload().expect(201); await request(app.getHttpServer()).get('/api/v1/files/' + file.id + '/download').set('Cookie', owner.cookie).expect(200); let cursor: string | null = null; const events: OpportunityHistoryPageDto['items'] = []; do {
    const response = await request(app.getHttpServer()).get('/api/v1/opportunities/' + row.id + '/history?pageSize=1' + (cursor ? '&after=' + encodeURIComponent(cursor) : '')).set('Cookie', owner.cookie).expect(200);
    const body = response.body as OpportunityHistoryPageDto;
    events.push(...body.items);
    cursor = body.nextCursor;
  } while (cursor); expect(events.map(event => event.kind)).toEqual(['CREATED', 'FILES_ATTACHED', 'DISCARDED']); expect(new Set(events.map(event => event.id)).size).toBe(3); expect((await service.recordedActivity()).items.filter(event => event.opportunityId === row.id).map(event => event.kind)).toEqual(['CREATED', 'DISCARDED']); });
});
