import { useInfiniteQuery, useMutation, useQuery, useQueryClient, type QueryClient, type InfiniteData } from '@tanstack/react-query';
import { AUTH_QUERY_KEY, type AuthIdentity } from '../auth/session';
import { apiRequest } from '../../lib/api/client';
import type { z } from 'zod';
import { historySchema, opportunityPageSchema, opportunitySchema } from './contracts';
import { invalidateDashboard } from '../home/dashboard-queries';
export const opportunityIdentityKey = (identity: AuthIdentity) => [identity.id, identity.role, [...identity.permissions].sort().join(',')] as const;
function assertIdentity(client: QueryClient, identity: AuthIdentity) { const current = client.getQueryData<AuthIdentity | null>(AUTH_QUERY_KEY); if (!current || opportunityIdentityKey(current).some((value, index) => value !== opportunityIdentityKey(identity)[index]))
  throw new DOMException('La identidad cambió.', 'AbortError'); }
export function useOpportunities(identity: AuthIdentity, path: string) { const client = useQueryClient(); return useQuery({ queryKey: ['opportunities', ...opportunityIdentityKey(identity), path], enabled: identity.permissions.includes('opportunities.read'), retry: false, queryFn: async ({ signal }) => { assertIdentity(client, identity); const data = await apiRequest(path, { signal }); assertIdentity(client, identity); return opportunityPageSchema.parse(data); } }); }
export function useOpportunity(identity: AuthIdentity, id: string) { const client = useQueryClient(); return useQuery({ queryKey: ['opportunities', ...opportunityIdentityKey(identity), id], enabled: !!id && identity.permissions.includes('opportunities.read'), retry: false, queryFn: async ({ signal }) => { assertIdentity(client, identity); const data = await apiRequest('opportunities/' + id, { signal }); assertIdentity(client, identity); return opportunitySchema.parse(data); } }); }
export function useOpportunityHistory(identity: AuthIdentity, id: string) { const client = useQueryClient(); return useInfiniteQuery<z.infer<typeof historySchema>, Error, InfiniteData<z.infer<typeof historySchema>>, readonly unknown[], string | null>({ queryKey: ['opportunity-history', ...opportunityIdentityKey(identity), id], enabled: identity.permissions.includes('opportunities.read') && identity.permissions.includes('files.read'), initialPageParam: null as string | null, getNextPageParam: page => page.nextCursor, retry: false, queryFn: async ({ signal, pageParam }) => { assertIdentity(client, identity); const data = await apiRequest('opportunities/' + id + '/history?pageSize=25' + (pageParam ? '&after=' + encodeURIComponent(pageParam) : ''), { signal }); assertIdentity(client, identity); return historySchema.parse(data); } }); }
export function useOpportunityMutation(identity: AuthIdentity, path: string, method: 'POST' | 'PATCH', permission: string) { const client = useQueryClient(); return useMutation({ retry: false, mutationFn: async ({ body, key }: {
    body: object;
    key?: string;
  }) => { assertIdentity(client, identity); if (!identity.permissions.includes(permission))
    throw new DOMException('Sin permiso.', 'AbortError'); const data = await apiRequest(path, { method, headers: { 'Content-Type': 'application/json', ...(key ? { 'Idempotency-Key': key } : {}) }, body: JSON.stringify(body) }); assertIdentity(client, identity); return opportunitySchema.parse(data); }, onSuccess: async (data) => { assertIdentity(client, identity); client.setQueryData(['opportunities', ...opportunityIdentityKey(identity), data.id], data); await Promise.all([client.invalidateQueries({ queryKey: ['opportunities'] }), client.invalidateQueries({ queryKey: ['opportunity-history'] }), invalidateDashboard(client, identity)]); } }); }
export async function clearForbiddenOpportunities(client: QueryClient, identity: AuthIdentity | null) { const prefix = identity ? opportunityIdentityKey(identity) : null; const predicate = (query: {
  queryKey: readonly unknown[];
}) => ['opportunities', 'opportunity-history'].includes(String(query.queryKey[0])) && (!identity?.permissions.includes('opportunities.read') || !prefix || prefix.some((value, index) => value !== query.queryKey[index + 1])); await client.cancelQueries({ predicate }); client.removeQueries({ predicate }); }
